from PySide import QtGui

class OdometryWidget(QtGui.QWidget):
    """This widget allows the user to configure the odometers."""
    def __init__(self, parent):
        super(OdometryWidget, self).__init__(parent)
        self.loadGUI()

    def loadGUI(self):
        """Load the GUI from the .py file that was generated by the .ui file
        using the pyside-uic tool."""
        # import generated .py file here to prevent circular reference
        from sim.view.odometry import Ui_odometry
        ui = Ui_odometry()
        ui.setupUi(self)


