from PySide import QtGui

class RobotWidget(QtGui.QWidget):
    """This widget allows the user to configure the robot."""
    def __init__(self, parent):
        super(RobotWidget, self).__init__(parent)
        self.loadGUI()

    def loadGUI(self):
        """Load the GUI from the .py file that was generated by the .ui file
        using the pyside-uic tool."""
        # import generated .py file here to prevent circular reference
        from sim.view.robot import Ui_robot
        ui = Ui_robot()
        ui.setupUi(self)

