# PySide imports
from PySide import QtGui, QtCore


class MainWindow(QtGui.QMainWindow):
    """The main window. This window displays all the widgets."""
    def __init__(self):
        super(MainWindow, self).__init__()
        self.loadGUI()

    def loadGUI(self):
        """Load the GUI from the .py file that was generated by the .ui file
        using the pyside-uic tool."""
        # import generated .py file here to prevent circular reference
        from sim.view.window import Ui_main_window
        ui = Ui_main_window()
        ui.setupUi(self)

