# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Tue Jun 11 13:53:25 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(982, 895)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphics_view = PlotGraphicsView(self.centralwidget)
        self.graphics_view.setMinimumSize(QtCore.QSize(0, 400))
        self.graphics_view.setLineWidth(2)
        self.graphics_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphics_view.setSceneRect(QtCore.QRectF(0.0, 0.0, 10.0, 10.0))
        self.graphics_view.setObjectName("graphics_view")
        self.gridLayout.addWidget(self.graphics_view, 2, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_23 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.pose_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.pose_label.setFont(font)
        self.pose_label.setTextFormat(QtCore.Qt.AutoText)
        self.pose_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pose_label.setObjectName("pose_label")
        self.gridLayout_9.addWidget(self.pose_label, 1, 1, 1, 1)
        self.velocity_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.velocity_label.setFont(font)
        self.velocity_label.setTextFormat(QtCore.Qt.AutoText)
        self.velocity_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.velocity_label.setObjectName("velocity_label")
        self.gridLayout_9.addWidget(self.velocity_label, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 2, 0, 1, 1)
        self.ang_vel_inc_box = QtGui.QSpinBox(self.groupBox)
        self.ang_vel_inc_box.setMaximumSize(QtCore.QSize(95, 16777215))
        self.ang_vel_inc_box.setMinimum(1)
        self.ang_vel_inc_box.setMaximum(60)
        self.ang_vel_inc_box.setObjectName("ang_vel_inc_box")
        self.gridLayout_9.addWidget(self.ang_vel_inc_box, 5, 1, 1, 1)
        self.vel_inc_box = QtGui.QDoubleSpinBox(self.groupBox)
        self.vel_inc_box.setMaximumSize(QtCore.QSize(95, 16777215))
        self.vel_inc_box.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.vel_inc_box.setMinimum(0.05)
        self.vel_inc_box.setMaximum(0.5)
        self.vel_inc_box.setSingleStep(0.05)
        self.vel_inc_box.setObjectName("vel_inc_box")
        self.gridLayout_9.addWidget(self.vel_inc_box, 4, 1, 1, 1)
        self.ang_vel_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.ang_vel_label.setFont(font)
        self.ang_vel_label.setTextFormat(QtCore.Qt.AutoText)
        self.ang_vel_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ang_vel_label.setObjectName("ang_vel_label")
        self.gridLayout_9.addWidget(self.ang_vel_label, 3, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 4, 0, 1, 1)
        self.laser_check = QtGui.QCheckBox(self.groupBox)
        self.laser_check.setText("")
        self.laser_check.setObjectName("laser_check")
        self.gridLayout_9.addWidget(self.laser_check, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.graphics_view_zoom = PlotGraphicsViewZoom(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view_zoom.sizePolicy().hasHeightForWidth())
        self.graphics_view_zoom.setSizePolicy(sizePolicy)
        self.graphics_view_zoom.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphics_view_zoom.setLineWidth(2)
        self.graphics_view_zoom.setObjectName("graphics_view_zoom")
        self.gridLayout.addWidget(self.graphics_view_zoom, 0, 1, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_11 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.load_map_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.load_map_button.setMinimumSize(QtCore.QSize(50, 50))
        self.load_map_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.load_map_button.setObjectName("load_map_button")
        self.gridLayout_11.addWidget(self.load_map_button, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayout_10 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.toggle_record_button = QtGui.QPushButton(self.tabWidgetPage2)
        self.toggle_record_button.setMinimumSize(QtCore.QSize(50, 50))
        self.toggle_record_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_record_button.setObjectName("toggle_record_button")
        self.gridLayout_10.addWidget(self.toggle_record_button, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 2, 0, 1, 1)
        self.record_timer_display = QtGui.QLabel(self.tabWidgetPage2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.record_timer_display.setFont(font)
        self.record_timer_display.setAlignment(QtCore.Qt.AlignCenter)
        self.record_timer_display.setObjectName("record_timer_display")
        self.gridLayout_10.addWidget(self.record_timer_display, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabWidgetPage3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_settings_button = QtGui.QPushButton(self.tabWidgetPage3)
        self.load_settings_button.setObjectName("load_settings_button")
        self.horizontalLayout.addWidget(self.load_settings_button)
        self.save_settings_button = QtGui.QPushButton(self.tabWidgetPage3)
        self.save_settings_button.setObjectName("save_settings_button")
        self.horizontalLayout.addWidget(self.save_settings_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.odom_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.odom_box.setFont(font)
        self.odom_box.setAlignment(QtCore.Qt.AlignCenter)
        self.odom_box.setObjectName("odom_box")
        self.gridLayout_5 = QtGui.QGridLayout(self.odom_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtGui.QLabel(self.odom_box)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.odom_freq_box = QtGui.QSpinBox(self.odom_box)
        self.odom_freq_box.setMinimum(1)
        self.odom_freq_box.setMaximum(20)
        self.odom_freq_box.setObjectName("odom_freq_box")
        self.gridLayout_6.addWidget(self.odom_freq_box, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.odom_box)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.odom_freq_slider = QtGui.QSlider(self.odom_box)
        self.odom_freq_slider.setMinimum(1)
        self.odom_freq_slider.setMaximum(20)
        self.odom_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_freq_slider.setInvertedAppearance(False)
        self.odom_freq_slider.setInvertedControls(False)
        self.odom_freq_slider.setObjectName("odom_freq_slider")
        self.gridLayout_6.addWidget(self.odom_freq_slider, 2, 1, 1, 1)
        self.odom_res_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_res_box.setMinimum(0.05)
        self.odom_res_box.setMaximum(2.0)
        self.odom_res_box.setSingleStep(0.05)
        self.odom_res_box.setObjectName("odom_res_box")
        self.gridLayout_6.addWidget(self.odom_res_box, 1, 2, 1, 1)
        self.odom_res_slider = QtGui.QSlider(self.odom_box)
        self.odom_res_slider.setMinimum(5)
        self.odom_res_slider.setMaximum(200)
        self.odom_res_slider.setSingleStep(5)
        self.odom_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_res_slider.setInvertedAppearance(True)
        self.odom_res_slider.setInvertedControls(False)
        self.odom_res_slider.setObjectName("odom_res_slider")
        self.gridLayout_6.addWidget(self.odom_res_slider, 1, 1, 1, 1)
        self.odom_noise_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_noise_box.setMinimum(0.1)
        self.odom_noise_box.setMaximum(3.0)
        self.odom_noise_box.setSingleStep(0.1)
        self.odom_noise_box.setObjectName("odom_noise_box")
        self.gridLayout_6.addWidget(self.odom_noise_box, 3, 2, 1, 1)
        self.odom_noise_slider = QtGui.QSlider(self.odom_box)
        self.odom_noise_slider.setMinimum(1)
        self.odom_noise_slider.setMaximum(30)
        self.odom_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_noise_slider.setInvertedAppearance(False)
        self.odom_noise_slider.setInvertedControls(False)
        self.odom_noise_slider.setObjectName("odom_noise_slider")
        self.gridLayout_6.addWidget(self.odom_noise_slider, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.odom_box)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.odom_box, 1, 0, 1, 1)
        self.robot_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_box.setFont(font)
        self.robot_box.setAlignment(QtCore.Qt.AlignCenter)
        self.robot_box.setObjectName("robot_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.robot_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robot_wheel_rad_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheel_rad_slider.setMinimum(5)
        self.robot_wheel_rad_slider.setMaximum(50)
        self.robot_wheel_rad_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheel_rad_slider.setInvertedAppearance(False)
        self.robot_wheel_rad_slider.setInvertedControls(False)
        self.robot_wheel_rad_slider.setObjectName("robot_wheel_rad_slider")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_slider, 4, 1, 1, 1)
        self.robot_wheelbase_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheelbase_slider.setMinimum(2)
        self.robot_wheelbase_slider.setMaximum(20)
        self.robot_wheelbase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheelbase_slider.setInvertedAppearance(False)
        self.robot_wheelbase_slider.setInvertedControls(False)
        self.robot_wheelbase_slider.setObjectName("robot_wheelbase_slider")
        self.gridLayout_2.addWidget(self.robot_wheelbase_slider, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.robot_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.robot_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.robot_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_vel_slider.setMinimum(1)
        self.robot_vel_slider.setMaximum(30)
        self.robot_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_vel_slider.setInvertedAppearance(False)
        self.robot_vel_slider.setInvertedControls(False)
        self.robot_vel_slider.setObjectName("robot_vel_slider")
        self.gridLayout_2.addWidget(self.robot_vel_slider, 6, 1, 1, 1)
        self.robot_length_slider = QtGui.QSlider(self.robot_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_length_slider.setFont(font)
        self.robot_length_slider.setMinimum(2)
        self.robot_length_slider.setMaximum(20)
        self.robot_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_length_slider.setObjectName("robot_length_slider")
        self.gridLayout_2.addWidget(self.robot_length_slider, 1, 1, 1, 1)
        self.robot_width_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_width_box.setMinimum(0.2)
        self.robot_width_box.setMaximum(2.0)
        self.robot_width_box.setSingleStep(0.1)
        self.robot_width_box.setObjectName("robot_width_box")
        self.gridLayout_2.addWidget(self.robot_width_box, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.robot_box)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.robot_width_slider = QtGui.QSlider(self.robot_box)
        self.robot_width_slider.setMinimum(2)
        self.robot_width_slider.setMaximum(20)
        self.robot_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_width_slider.setInvertedAppearance(False)
        self.robot_width_slider.setInvertedControls(False)
        self.robot_width_slider.setObjectName("robot_width_slider")
        self.gridLayout_2.addWidget(self.robot_width_slider, 3, 1, 1, 1)
        self.robot_wheel_rad_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheel_rad_box.setMinimum(0.05)
        self.robot_wheel_rad_box.setMaximum(0.5)
        self.robot_wheel_rad_box.setSingleStep(0.01)
        self.robot_wheel_rad_box.setObjectName("robot_wheel_rad_box")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_box, 4, 2, 1, 1)
        self.label = QtGui.QLabel(self.robot_box)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.robot_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.robot_box)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.robot_length_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_length_box.setMinimum(0.2)
        self.robot_length_box.setMaximum(2.0)
        self.robot_length_box.setSingleStep(0.1)
        self.robot_length_box.setObjectName("robot_length_box")
        self.gridLayout_2.addWidget(self.robot_length_box, 1, 2, 1, 1)
        self.robot_ang_vel_box = QtGui.QSpinBox(self.robot_box)
        self.robot_ang_vel_box.setMinimum(5)
        self.robot_ang_vel_box.setMaximum(60)
        self.robot_ang_vel_box.setObjectName("robot_ang_vel_box")
        self.gridLayout_2.addWidget(self.robot_ang_vel_box, 7, 2, 1, 1)
        self.robot_ang_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_ang_vel_slider.setMinimum(5)
        self.robot_ang_vel_slider.setMaximum(60)
        self.robot_ang_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_ang_vel_slider.setInvertedAppearance(False)
        self.robot_ang_vel_slider.setInvertedControls(False)
        self.robot_ang_vel_slider.setObjectName("robot_ang_vel_slider")
        self.gridLayout_2.addWidget(self.robot_ang_vel_slider, 7, 1, 1, 1)
        self.robot_wheelbase_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheelbase_box.setMinimum(0.2)
        self.robot_wheelbase_box.setMaximum(2.0)
        self.robot_wheelbase_box.setSingleStep(0.1)
        self.robot_wheelbase_box.setObjectName("robot_wheelbase_box")
        self.gridLayout_2.addWidget(self.robot_wheelbase_box, 5, 2, 1, 1)
        self.robot_vel_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_vel_box.setMinimum(0.1)
        self.robot_vel_box.setMaximum(3.0)
        self.robot_vel_box.setSingleStep(0.1)
        self.robot_vel_box.setObjectName("robot_vel_box")
        self.gridLayout_2.addWidget(self.robot_vel_box, 6, 2, 1, 1)
        self.robot_combo = QtGui.QComboBox(self.robot_box)
        self.robot_combo.setObjectName("robot_combo")
        self.gridLayout_2.addWidget(self.robot_combo, 0, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.robot_box)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 6, 1, 1)
        self.gridLayout_4.addWidget(self.robot_box, 0, 0, 1, 1)
        self.laser_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.laser_box.setFont(font)
        self.laser_box.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_box.setObjectName("laser_box")
        self.gridLayout_7 = QtGui.QGridLayout(self.laser_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtGui.QLabel(self.laser_box)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.laser_noise_box = QtGui.QSpinBox(self.laser_box)
        self.laser_noise_box.setMinimum(1)
        self.laser_noise_box.setMaximum(15)
        self.laser_noise_box.setObjectName("laser_noise_box")
        self.gridLayout_8.addWidget(self.laser_noise_box, 8, 2, 1, 1)
        self.laser_res_box = QtGui.QDoubleSpinBox(self.laser_box)
        self.laser_res_box.setMinimum(0.2)
        self.laser_res_box.setMaximum(5.0)
        self.laser_res_box.setSingleStep(0.1)
        self.laser_res_box.setObjectName("laser_res_box")
        self.gridLayout_8.addWidget(self.laser_res_box, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.laser_box)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 1)
        self.laser_range_box = QtGui.QSpinBox(self.laser_box)
        self.laser_range_box.setMinimum(1)
        self.laser_range_box.setMaximum(25)
        self.laser_range_box.setObjectName("laser_range_box")
        self.gridLayout_8.addWidget(self.laser_range_box, 2, 2, 1, 1)
        self.laser_min_bear_box = QtGui.QSpinBox(self.laser_box)
        self.laser_min_bear_box.setMinimum(-180)
        self.laser_min_bear_box.setMaximum(180)
        self.laser_min_bear_box.setProperty("value", -90)
        self.laser_min_bear_box.setObjectName("laser_min_bear_box")
        self.gridLayout_8.addWidget(self.laser_min_bear_box, 4, 2, 1, 1)
        self.laser_res_slider = QtGui.QSlider(self.laser_box)
        self.laser_res_slider.setMinimum(2)
        self.laser_res_slider.setMaximum(50)
        self.laser_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider.setInvertedAppearance(True)
        self.laser_res_slider.setInvertedControls(False)
        self.laser_res_slider.setObjectName("laser_res_slider")
        self.gridLayout_8.addWidget(self.laser_res_slider, 6, 1, 1, 1)
        self.laser_noise_slider = QtGui.QSlider(self.laser_box)
        self.laser_noise_slider.setMinimum(1)
        self.laser_noise_slider.setMaximum(15)
        self.laser_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_noise_slider.setInvertedAppearance(False)
        self.laser_noise_slider.setInvertedControls(False)
        self.laser_noise_slider.setObjectName("laser_noise_slider")
        self.gridLayout_8.addWidget(self.laser_noise_slider, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.laser_box)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 6, 0, 1, 1)
        self.laser_freq_box = QtGui.QSpinBox(self.laser_box)
        self.laser_freq_box.setMinimum(1)
        self.laser_freq_box.setMaximum(15)
        self.laser_freq_box.setObjectName("laser_freq_box")
        self.gridLayout_8.addWidget(self.laser_freq_box, 7, 2, 1, 1)
        self.laser_range_slider = QtGui.QSlider(self.laser_box)
        self.laser_range_slider.setMinimum(1)
        self.laser_range_slider.setMaximum(25)
        self.laser_range_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_range_slider.setObjectName("laser_range_slider")
        self.gridLayout_8.addWidget(self.laser_range_slider, 2, 1, 1, 1)
        self.laser_min_bear_slider = QtGui.QSlider(self.laser_box)
        self.laser_min_bear_slider.setMinimum(-180)
        self.laser_min_bear_slider.setMaximum(180)
        self.laser_min_bear_slider.setProperty("value", -90)
        self.laser_min_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_min_bear_slider.setInvertedAppearance(False)
        self.laser_min_bear_slider.setInvertedControls(False)
        self.laser_min_bear_slider.setObjectName("laser_min_bear_slider")
        self.gridLayout_8.addWidget(self.laser_min_bear_slider, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.laser_box)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.laser_box)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 7, 0, 1, 1)
        self.laser_combo = QtGui.QComboBox(self.laser_box)
        self.laser_combo.setObjectName("laser_combo")
        self.gridLayout_8.addWidget(self.laser_combo, 1, 1, 1, 2)
        self.laser_freq_slider = QtGui.QSlider(self.laser_box)
        self.laser_freq_slider.setMinimum(1)
        self.laser_freq_slider.setMaximum(15)
        self.laser_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_freq_slider.setInvertedAppearance(False)
        self.laser_freq_slider.setInvertedControls(False)
        self.laser_freq_slider.setObjectName("laser_freq_slider")
        self.gridLayout_8.addWidget(self.laser_freq_slider, 7, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.laser_box)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.laser_box)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 5, 0, 1, 1)
        self.laser_max_bear_slider = QtGui.QSlider(self.laser_box)
        self.laser_max_bear_slider.setMinimum(-180)
        self.laser_max_bear_slider.setMaximum(180)
        self.laser_max_bear_slider.setProperty("value", 90)
        self.laser_max_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_max_bear_slider.setInvertedAppearance(False)
        self.laser_max_bear_slider.setInvertedControls(False)
        self.laser_max_bear_slider.setObjectName("laser_max_bear_slider")
        self.gridLayout_8.addWidget(self.laser_max_bear_slider, 5, 1, 1, 1)
        self.laser_max_bear_box = QtGui.QSpinBox(self.laser_box)
        self.laser_max_bear_box.setMinimum(-180)
        self.laser_max_bear_box.setMaximum(180)
        self.laser_max_bear_box.setProperty("value", 90)
        self.laser_max_bear_box.setObjectName("laser_max_bear_box")
        self.gridLayout_8.addWidget(self.laser_max_bear_box, 5, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 3, 6, 1, 1)
        self.gridLayout_4.addWidget(self.laser_box, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 3, 1)
        self.logo_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(259, 113))
        self.logo_label.setMaximumSize(QtCore.QSize(259, 113))
        self.logo_label.setText("")
        self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.logo_label.setObjectName("logo_label")
        self.gridLayout.addWidget(self.logo_label, 0, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "MSL Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("main_window", "Show laser beams", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("main_window", "Pose:", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.velocity_label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("main_window", "Angular velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("main_window", "Velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.ang_vel_inc_box.setSuffix(QtGui.QApplication.translate("main_window", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.vel_inc_box.setSuffix(QtGui.QApplication.translate("main_window", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.ang_vel_label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("main_window", "Ang. vel. increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("main_window", "Velocity increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.load_map_button.setText(QtGui.QApplication.translate("main_window", "Load Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("main_window", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_record_button.setText(QtGui.QApplication.translate("main_window", "Start Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.record_timer_display.setText(QtGui.QApplication.translate("main_window", "Elapsed time: 0.00 s", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("main_window", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.load_settings_button.setText(QtGui.QApplication.translate("main_window", "Load settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_settings_button.setText(QtGui.QApplication.translate("main_window", "Save settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_box.setTitle(QtGui.QApplication.translate("main_window", "Odometry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("main_window", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_freq_box.setSuffix(QtGui.QApplication.translate("main_window", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("main_window", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_res_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_noise_box.setSuffix(QtGui.QApplication.translate("main_window", " ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("main_window", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_box.setTitle(QtGui.QApplication.translate("main_window", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("main_window", "Wheelbase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main_window", "Max velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_width_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main_window", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheel_rad_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main_window", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("main_window", "Wheel radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("main_window", "Max angular velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_length_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_ang_vel_box.setSuffix(QtGui.QApplication.translate("main_window", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheelbase_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_vel_box.setSuffix(QtGui.QApplication.translate("main_window", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("main_window", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_box.setTitle(QtGui.QApplication.translate("main_window", "Laser ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("main_window", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_noise_box.setSuffix(QtGui.QApplication.translate("main_window", " cm", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_res_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("main_window", "Min bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_range_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_min_bear_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("main_window", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_freq_box.setSuffix(QtGui.QApplication.translate("main_window", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("main_window", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("main_window", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("main_window", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("main_window", "Max bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_max_bear_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), QtGui.QApplication.translate("main_window", "Settings", None, QtGui.QApplication.UnicodeUTF8))

from sim.controller import PlotGraphicsViewZoom, PlotGraphicsView
