# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Wed May 29 13:32:14 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1079, 808)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.settings = QtGui.QWidget()
        self.settings.setObjectName("settings")
        self.gridLayout_4 = QtGui.QGridLayout(self.settings)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_settings_button = QtGui.QPushButton(self.settings)
        self.load_settings_button.setObjectName("load_settings_button")
        self.horizontalLayout.addWidget(self.load_settings_button)
        self.save_settings_button = QtGui.QPushButton(self.settings)
        self.save_settings_button.setObjectName("save_settings_button")
        self.horizontalLayout.addWidget(self.save_settings_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.odom_box = QtGui.QGroupBox(self.settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.odom_box.setFont(font)
        self.odom_box.setAlignment(QtCore.Qt.AlignCenter)
        self.odom_box.setObjectName("odom_box")
        self.gridLayout_5 = QtGui.QGridLayout(self.odom_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.odom_freq_slider = QtGui.QSlider(self.odom_box)
        self.odom_freq_slider.setMinimum(1)
        self.odom_freq_slider.setMaximum(30)
        self.odom_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_freq_slider.setInvertedAppearance(False)
        self.odom_freq_slider.setInvertedControls(False)
        self.odom_freq_slider.setObjectName("odom_freq_slider")
        self.gridLayout_6.addWidget(self.odom_freq_slider, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.odom_box)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.odom_res_slider = QtGui.QSlider(self.odom_box)
        self.odom_res_slider.setMinimum(5)
        self.odom_res_slider.setMaximum(30)
        self.odom_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_res_slider.setInvertedAppearance(False)
        self.odom_res_slider.setInvertedControls(False)
        self.odom_res_slider.setObjectName("odom_res_slider")
        self.gridLayout_6.addWidget(self.odom_res_slider, 1, 1, 1, 1)
        self.odom_res_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_res_box.setMinimum(0.5)
        self.odom_res_box.setMaximum(3.0)
        self.odom_res_box.setSingleStep(0.1)
        self.odom_res_box.setObjectName("odom_res_box")
        self.gridLayout_6.addWidget(self.odom_res_box, 1, 2, 1, 1)
        self.odom_noise_slider = QtGui.QSlider(self.odom_box)
        self.odom_noise_slider.setMinimum(1)
        self.odom_noise_slider.setMaximum(30)
        self.odom_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_noise_slider.setInvertedAppearance(False)
        self.odom_noise_slider.setInvertedControls(False)
        self.odom_noise_slider.setObjectName("odom_noise_slider")
        self.gridLayout_6.addWidget(self.odom_noise_slider, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.odom_box)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.odom_freq_box = QtGui.QSpinBox(self.odom_box)
        self.odom_freq_box.setMinimum(1)
        self.odom_freq_box.setMaximum(30)
        self.odom_freq_box.setObjectName("odom_freq_box")
        self.gridLayout_6.addWidget(self.odom_freq_box, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.odom_box)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.odom_noise_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_noise_box.setMinimum(0.1)
        self.odom_noise_box.setMaximum(3.0)
        self.odom_noise_box.setSingleStep(0.1)
        self.odom_noise_box.setObjectName("odom_noise_box")
        self.gridLayout_6.addWidget(self.odom_noise_box, 3, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.odom_box, 1, 0, 1, 1)
        self.robot_box = QtGui.QGroupBox(self.settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_box.setFont(font)
        self.robot_box.setAlignment(QtCore.Qt.AlignCenter)
        self.robot_box.setObjectName("robot_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.robot_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robot_wheel_rad_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheel_rad_slider.setMinimum(10)
        self.robot_wheel_rad_slider.setMaximum(50)
        self.robot_wheel_rad_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheel_rad_slider.setInvertedAppearance(False)
        self.robot_wheel_rad_slider.setInvertedControls(False)
        self.robot_wheel_rad_slider.setObjectName("robot_wheel_rad_slider")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_slider, 3, 1, 1, 1)
        self.robot_wheelbase_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheelbase_slider.setMinimum(5)
        self.robot_wheelbase_slider.setMaximum(20)
        self.robot_wheelbase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheelbase_slider.setInvertedAppearance(False)
        self.robot_wheelbase_slider.setInvertedControls(False)
        self.robot_wheelbase_slider.setObjectName("robot_wheelbase_slider")
        self.gridLayout_2.addWidget(self.robot_wheelbase_slider, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.robot_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.robot_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.robot_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_vel_slider.setMinimum(1)
        self.robot_vel_slider.setMaximum(30)
        self.robot_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_vel_slider.setInvertedAppearance(False)
        self.robot_vel_slider.setInvertedControls(False)
        self.robot_vel_slider.setObjectName("robot_vel_slider")
        self.gridLayout_2.addWidget(self.robot_vel_slider, 5, 1, 1, 1)
        self.robot_width_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_width_box.setMinimum(0.5)
        self.robot_width_box.setMaximum(2.0)
        self.robot_width_box.setSingleStep(0.1)
        self.robot_width_box.setObjectName("robot_width_box")
        self.gridLayout_2.addWidget(self.robot_width_box, 2, 2, 1, 1)
        self.robot_length_slider = QtGui.QSlider(self.robot_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_length_slider.setFont(font)
        self.robot_length_slider.setMinimum(5)
        self.robot_length_slider.setMaximum(20)
        self.robot_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_length_slider.setObjectName("robot_length_slider")
        self.gridLayout_2.addWidget(self.robot_length_slider, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.robot_box)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.robot_width_slider = QtGui.QSlider(self.robot_box)
        self.robot_width_slider.setMinimum(5)
        self.robot_width_slider.setMaximum(20)
        self.robot_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_width_slider.setInvertedAppearance(False)
        self.robot_width_slider.setInvertedControls(False)
        self.robot_width_slider.setObjectName("robot_width_slider")
        self.gridLayout_2.addWidget(self.robot_width_slider, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.robot_box)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.robot_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.robot_wheel_rad_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheel_rad_box.setMinimum(0.1)
        self.robot_wheel_rad_box.setMaximum(0.5)
        self.robot_wheel_rad_box.setSingleStep(0.01)
        self.robot_wheel_rad_box.setObjectName("robot_wheel_rad_box")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_box, 3, 2, 1, 1)
        self.robot_length_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_length_box.setMinimum(0.5)
        self.robot_length_box.setMaximum(2.0)
        self.robot_length_box.setSingleStep(0.1)
        self.robot_length_box.setObjectName("robot_length_box")
        self.gridLayout_2.addWidget(self.robot_length_box, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.robot_box)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.robot_ang_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_ang_vel_slider.setMinimum(5)
        self.robot_ang_vel_slider.setMaximum(60)
        self.robot_ang_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_ang_vel_slider.setInvertedAppearance(False)
        self.robot_ang_vel_slider.setInvertedControls(False)
        self.robot_ang_vel_slider.setObjectName("robot_ang_vel_slider")
        self.gridLayout_2.addWidget(self.robot_ang_vel_slider, 6, 1, 1, 1)
        self.robot_ang_vel_box = QtGui.QSpinBox(self.robot_box)
        self.robot_ang_vel_box.setMinimum(5)
        self.robot_ang_vel_box.setMaximum(60)
        self.robot_ang_vel_box.setObjectName("robot_ang_vel_box")
        self.gridLayout_2.addWidget(self.robot_ang_vel_box, 6, 2, 1, 1)
        self.robot_wheelbase_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheelbase_box.setMinimum(0.5)
        self.robot_wheelbase_box.setMaximum(2.0)
        self.robot_wheelbase_box.setSingleStep(0.1)
        self.robot_wheelbase_box.setObjectName("robot_wheelbase_box")
        self.gridLayout_2.addWidget(self.robot_wheelbase_box, 4, 2, 1, 1)
        self.robot_vel_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_vel_box.setMinimum(0.1)
        self.robot_vel_box.setMaximum(3.0)
        self.robot_vel_box.setSingleStep(0.1)
        self.robot_vel_box.setObjectName("robot_vel_box")
        self.gridLayout_2.addWidget(self.robot_vel_box, 5, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.robot_box, 0, 0, 1, 1)
        self.laser_box = QtGui.QGroupBox(self.settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.laser_box.setFont(font)
        self.laser_box.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_box.setObjectName("laser_box")
        self.gridLayout_7 = QtGui.QGridLayout(self.laser_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.laser_range_slider = QtGui.QSlider(self.laser_box)
        self.laser_range_slider.setMinimum(1)
        self.laser_range_slider.setMaximum(25)
        self.laser_range_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_range_slider.setObjectName("laser_range_slider")
        self.gridLayout_8.addWidget(self.laser_range_slider, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.laser_box)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 1)
        self.laser_fov_slider = QtGui.QSlider(self.laser_box)
        self.laser_fov_slider.setMinimum(10)
        self.laser_fov_slider.setMaximum(360)
        self.laser_fov_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_fov_slider.setInvertedAppearance(False)
        self.laser_fov_slider.setInvertedControls(False)
        self.laser_fov_slider.setObjectName("laser_fov_slider")
        self.gridLayout_8.addWidget(self.laser_fov_slider, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.laser_box)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.laser_fov_box = QtGui.QSpinBox(self.laser_box)
        self.laser_fov_box.setMinimum(10)
        self.laser_fov_box.setMaximum(360)
        self.laser_fov_box.setObjectName("laser_fov_box")
        self.gridLayout_8.addWidget(self.laser_fov_box, 2, 2, 1, 1)
        self.laser_range_box = QtGui.QSpinBox(self.laser_box)
        self.laser_range_box.setMinimum(1)
        self.laser_range_box.setMaximum(25)
        self.laser_range_box.setObjectName("laser_range_box")
        self.gridLayout_8.addWidget(self.laser_range_box, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.laser_box)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 3, 0, 1, 1)
        self.laser_res_box = QtGui.QDoubleSpinBox(self.laser_box)
        self.laser_res_box.setMinimum(0.2)
        self.laser_res_box.setMaximum(5.0)
        self.laser_res_box.setSingleStep(0.1)
        self.laser_res_box.setObjectName("laser_res_box")
        self.gridLayout_8.addWidget(self.laser_res_box, 3, 2, 1, 1)
        self.laser_res_slider = QtGui.QSlider(self.laser_box)
        self.laser_res_slider.setMinimum(2)
        self.laser_res_slider.setMaximum(50)
        self.laser_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider.setInvertedAppearance(False)
        self.laser_res_slider.setInvertedControls(False)
        self.laser_res_slider.setObjectName("laser_res_slider")
        self.gridLayout_8.addWidget(self.laser_res_slider, 3, 1, 1, 1)
        self.laser_freq_slider = QtGui.QSlider(self.laser_box)
        self.laser_freq_slider.setMinimum(1)
        self.laser_freq_slider.setMaximum(15)
        self.laser_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_freq_slider.setInvertedAppearance(False)
        self.laser_freq_slider.setInvertedControls(False)
        self.laser_freq_slider.setObjectName("laser_freq_slider")
        self.gridLayout_8.addWidget(self.laser_freq_slider, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.laser_box)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 4, 0, 1, 1)
        self.laser_freq_box = QtGui.QSpinBox(self.laser_box)
        self.laser_freq_box.setMinimum(1)
        self.laser_freq_box.setMaximum(15)
        self.laser_freq_box.setObjectName("laser_freq_box")
        self.gridLayout_8.addWidget(self.laser_freq_box, 4, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.laser_box)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 5, 0, 1, 1)
        self.laser_noise_slider = QtGui.QSlider(self.laser_box)
        self.laser_noise_slider.setMinimum(1)
        self.laser_noise_slider.setMaximum(15)
        self.laser_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_noise_slider.setInvertedAppearance(False)
        self.laser_noise_slider.setInvertedControls(False)
        self.laser_noise_slider.setObjectName("laser_noise_slider")
        self.gridLayout_8.addWidget(self.laser_noise_slider, 5, 1, 1, 1)
        self.laser_noise_box = QtGui.QSpinBox(self.laser_box)
        self.laser_noise_box.setMinimum(1)
        self.laser_noise_box.setMaximum(15)
        self.laser_noise_box.setObjectName("laser_noise_box")
        self.gridLayout_8.addWidget(self.laser_noise_box, 5, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.laser_box, 2, 0, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 3, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphics_view = PlotGraphicsView(self.centralwidget)
        self.graphics_view.setMinimumSize(QtCore.QSize(600, 0))
        self.graphics_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphics_view.setSceneRect(QtCore.QRectF(0.0, 0.0, 10.0, 10.0))
        self.graphics_view.setObjectName("graphics_view")
        self.gridLayout.addWidget(self.graphics_view, 1, 0, 1, 3)
        self.graphics_view_zoom = PlotGraphicsViewZoom(self.centralwidget)
        self.graphics_view_zoom.setObjectName("graphics_view_zoom")
        self.gridLayout.addWidget(self.graphics_view_zoom, 0, 1, 1, 2)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "MSL Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("main_window", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("main_window", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.load_settings_button.setText(QtGui.QApplication.translate("main_window", "Load settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_settings_button.setText(QtGui.QApplication.translate("main_window", "Save settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_box.setTitle(QtGui.QApplication.translate("main_window", "Odometry Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("main_window", "Resolution [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("main_window", "Noise [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("main_window", "Frequency [Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_box.setTitle(QtGui.QApplication.translate("main_window", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("main_window", "Wheelbase [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main_window", "Max velocity [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main_window", "Width [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main_window", "Length [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("main_window", "Wheel radius [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("main_window", "Max angular velocity [deg/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_box.setTitle(QtGui.QApplication.translate("main_window", "Laser Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("main_window", "FOV [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("main_window", "Range [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("main_window", "Resolution [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("main_window", "Frequency [Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("main_window", "Noise [cm]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("main_window", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("main_window", "Information", None, QtGui.QApplication.UnicodeUTF8))

from sim.controller import PlotGraphicsViewZoom, PlotGraphicsView
