# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Mon Jun 17 16:47:26 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1136, 945)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphics_view = PlotGraphicsView(self.centralwidget)
        self.graphics_view.setMinimumSize(QtCore.QSize(0, 0))
        self.graphics_view.setLineWidth(2)
        self.graphics_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphics_view.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphics_view.setObjectName("graphics_view")
        self.gridLayout.addWidget(self.graphics_view, 2, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 220))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 3, 0, 1, 1)
        self.vel_inc_box = QtGui.QDoubleSpinBox(self.groupBox)
        self.vel_inc_box.setMinimumSize(QtCore.QSize(0, 22))
        self.vel_inc_box.setMaximumSize(QtCore.QSize(90, 16777215))
        self.vel_inc_box.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.vel_inc_box.setMinimum(0.05)
        self.vel_inc_box.setMaximum(0.5)
        self.vel_inc_box.setSingleStep(0.05)
        self.vel_inc_box.setObjectName("vel_inc_box")
        self.gridLayout_9.addWidget(self.vel_inc_box, 3, 1, 1, 2)
        self.pose_label = QtGui.QLabel(self.groupBox)
        self.pose_label.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.pose_label.setFont(font)
        self.pose_label.setTextFormat(QtCore.Qt.AutoText)
        self.pose_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pose_label.setObjectName("pose_label")
        self.gridLayout_9.addWidget(self.pose_label, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 5, 0, 1, 1)
        self.velocity_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.velocity_label.setFont(font)
        self.velocity_label.setTextFormat(QtCore.Qt.AutoText)
        self.velocity_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.velocity_label.setObjectName("velocity_label")
        self.gridLayout_9.addWidget(self.velocity_label, 1, 1, 1, 1)
        self.ang_vel_inc_box = QtGui.QSpinBox(self.groupBox)
        self.ang_vel_inc_box.setMinimumSize(QtCore.QSize(0, 22))
        self.ang_vel_inc_box.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ang_vel_inc_box.setMinimum(1)
        self.ang_vel_inc_box.setMaximum(60)
        self.ang_vel_inc_box.setObjectName("ang_vel_inc_box")
        self.gridLayout_9.addWidget(self.ang_vel_inc_box, 4, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(-1)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zoom_in_button = QtGui.QPushButton(self.groupBox)
        self.zoom_in_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.horizontalLayout_4.addWidget(self.zoom_in_button)
        self.zoom_out_button = QtGui.QPushButton(self.groupBox)
        self.zoom_out_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.zoom_out_button.setObjectName("zoom_out_button")
        self.horizontalLayout_4.addWidget(self.zoom_out_button)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 6, 1, 1, 1)
        self.ang_vel_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.ang_vel_label.setFont(font)
        self.ang_vel_label.setTextFormat(QtCore.Qt.AutoText)
        self.ang_vel_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ang_vel_label.setObjectName("ang_vel_label")
        self.gridLayout_9.addWidget(self.ang_vel_label, 2, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 6, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.laser_check = QtGui.QCheckBox(self.groupBox)
        self.laser_check.setText("")
        self.laser_check.setChecked(True)
        self.laser_check.setObjectName("laser_check")
        self.horizontalLayout_5.addWidget(self.laser_check)
        self.label_48 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setTextFormat(QtCore.Qt.AutoText)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setWordWrap(False)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.map_check = QtGui.QCheckBox(self.groupBox)
        self.map_check.setText("")
        self.map_check.setChecked(True)
        self.map_check.setObjectName("map_check")
        self.horizontalLayout_5.addWidget(self.map_check)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.logo_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(259, 113))
        self.logo_label.setMaximumSize(QtCore.QSize(259, 113))
        self.logo_label.setText("")
        self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.logo_label.setObjectName("logo_label")
        self.gridLayout.addWidget(self.logo_label, 0, 0, 1, 1)
        self.graphics_view_zoom = PlotGraphicsViewZoom(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view_zoom.sizePolicy().hasHeightForWidth())
        self.graphics_view_zoom.setSizePolicy(sizePolicy)
        self.graphics_view_zoom.setMinimumSize(QtCore.QSize(200, 0))
        self.graphics_view_zoom.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphics_view_zoom.setLineWidth(2)
        self.graphics_view_zoom.setObjectName("graphics_view_zoom")
        self.gridLayout.addWidget(self.graphics_view_zoom, 0, 1, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_11 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_2 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.draw_line_button = QtGui.QPushButton(self.groupBox_2)
        self.draw_line_button.setMinimumSize(QtCore.QSize(0, 35))
        self.draw_line_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.draw_line_button.setObjectName("draw_line_button")
        self.horizontalLayout_2.addWidget(self.draw_line_button)
        self.freehand_line_button = QtGui.QPushButton(self.groupBox_2)
        self.freehand_line_button.setMinimumSize(QtCore.QSize(0, 35))
        self.freehand_line_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.freehand_line_button.setObjectName("freehand_line_button")
        self.horizontalLayout_2.addWidget(self.freehand_line_button)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)
        self.line_angle_box = QtGui.QSpinBox(self.groupBox_2)
        self.line_angle_box.setMaximum(180)
        self.line_angle_box.setObjectName("line_angle_box")
        self.gridLayout_12.addWidget(self.line_angle_box, 4, 2, 1, 2)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 1, 2, 1, 1)
        self.line_thickness_box = QtGui.QSpinBox(self.groupBox_2)
        self.line_thickness_box.setMaximum(180)
        self.line_thickness_box.setObjectName("line_thickness_box")
        self.gridLayout_12.addWidget(self.line_thickness_box, 1, 2, 1, 2)
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 4, 0, 1, 1)
        self.line_length_box = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.line_length_box.setMinimum(0.1)
        self.line_length_box.setMaximum(20.0)
        self.line_length_box.setSingleStep(0.1)
        self.line_length_box.setProperty("value", 2.0)
        self.line_length_box.setObjectName("line_length_box")
        self.gridLayout_12.addWidget(self.line_length_box, 2, 2, 1, 2)
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_12.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 2, 0, 1, 1)
        self.line_thickness_slider = QtGui.QSlider(self.groupBox_2)
        self.line_thickness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_thickness_slider.setObjectName("line_thickness_slider")
        self.gridLayout_12.addWidget(self.line_thickness_slider, 1, 1, 1, 1)
        self.line_length_slider = QtGui.QSlider(self.groupBox_2)
        self.line_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_length_slider.setObjectName("line_length_slider")
        self.gridLayout_12.addWidget(self.line_length_slider, 2, 1, 1, 1)
        self.line_angle_slider = QtGui.QSlider(self.groupBox_2)
        self.line_angle_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_angle_slider.setObjectName("line_angle_slider")
        self.gridLayout_12.addWidget(self.line_angle_slider, 4, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.load_map_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.load_map_button.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_map_button.sizePolicy().hasHeightForWidth())
        self.load_map_button.setSizePolicy(sizePolicy)
        self.load_map_button.setMinimumSize(QtCore.QSize(0, 0))
        self.load_map_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.load_map_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.load_map_button.setObjectName("load_map_button")
        self.gridLayout_11.addWidget(self.load_map_button, 3, 0, 1, 1)
        self.save_map_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.save_map_button.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_map_button.sizePolicy().hasHeightForWidth())
        self.save_map_button.setSizePolicy(sizePolicy)
        self.save_map_button.setMinimumSize(QtCore.QSize(0, 0))
        self.save_map_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.save_map_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_map_button.setObjectName("save_map_button")
        self.gridLayout_11.addWidget(self.save_map_button, 3, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.polygon_size_box = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.polygon_size_box.setMinimum(0.05)
        self.polygon_size_box.setMaximum(3.0)
        self.polygon_size_box.setSingleStep(0.05)
        self.polygon_size_box.setProperty("value", 0.4)
        self.polygon_size_box.setObjectName("polygon_size_box")
        self.gridLayout_16.addWidget(self.polygon_size_box, 2, 3, 1, 2)
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_16.addWidget(self.label_27, 3, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_16.addWidget(self.label_25, 1, 1, 1, 1)
        self.polygon_angle_box = QtGui.QSpinBox(self.groupBox_4)
        self.polygon_angle_box.setMaximum(180)
        self.polygon_angle_box.setObjectName("polygon_angle_box")
        self.gridLayout_16.addWidget(self.polygon_angle_box, 3, 3, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.draw_polygon_button = QtGui.QPushButton(self.groupBox_4)
        self.draw_polygon_button.setMinimumSize(QtCore.QSize(0, 35))
        self.draw_polygon_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.draw_polygon_button.setObjectName("draw_polygon_button")
        self.horizontalLayout_3.addWidget(self.draw_polygon_button)
        self.random_polygon_button = QtGui.QPushButton(self.groupBox_4)
        self.random_polygon_button.setMinimumSize(QtCore.QSize(0, 35))
        self.random_polygon_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.random_polygon_button.setObjectName("random_polygon_button")
        self.horizontalLayout_3.addWidget(self.random_polygon_button)
        self.gridLayout_16.addLayout(self.horizontalLayout_3, 0, 1, 1, 4)
        self.polygon_size_slider = QtGui.QSlider(self.groupBox_4)
        self.polygon_size_slider.setMinimum(5)
        self.polygon_size_slider.setMaximum(300)
        self.polygon_size_slider.setProperty("value", 40)
        self.polygon_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.polygon_size_slider.setObjectName("polygon_size_slider")
        self.gridLayout_16.addWidget(self.polygon_size_slider, 2, 2, 1, 1)
        self.polygon_angle_slider = QtGui.QSlider(self.groupBox_4)
        self.polygon_angle_slider.setMaximum(180)
        self.polygon_angle_slider.setOrientation(QtCore.Qt.Horizontal)
        self.polygon_angle_slider.setObjectName("polygon_angle_slider")
        self.gridLayout_16.addWidget(self.polygon_angle_slider, 3, 2, 1, 1)
        self.polygon_edges_combo = QtGui.QComboBox(self.groupBox_4)
        self.polygon_edges_combo.setObjectName("polygon_edges_combo")
        self.polygon_edges_combo.addItem("")
        self.polygon_edges_combo.addItem("")
        self.polygon_edges_combo.addItem("")
        self.polygon_edges_combo.addItem("")
        self.gridLayout_16.addWidget(self.polygon_edges_combo, 1, 2, 1, 3)
        self.gridLayout_11.addWidget(self.groupBox_4, 1, 0, 1, 3)
        self.clear_map_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.clear_map_button.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_map_button.sizePolicy().hasHeightForWidth())
        self.clear_map_button.setSizePolicy(sizePolicy)
        self.clear_map_button.setMinimumSize(QtCore.QSize(0, 0))
        self.clear_map_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clear_map_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_map_button.setObjectName("clear_map_button")
        self.gridLayout_11.addWidget(self.clear_map_button, 3, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_13.addWidget(self.label_34, 4, 0, 1, 2)
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 2, 0, 1, 2)
        self.num_obstacles_box = QtGui.QSpinBox(self.groupBox_3)
        self.num_obstacles_box.setMinimum(1)
        self.num_obstacles_box.setMaximum(250)
        self.num_obstacles_box.setProperty("value", 50)
        self.num_obstacles_box.setObjectName("num_obstacles_box")
        self.gridLayout_13.addWidget(self.num_obstacles_box, 1, 3, 1, 2)
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 1, 0, 1, 2)
        self.mean_diameter_slider = QtGui.QSlider(self.groupBox_3)
        self.mean_diameter_slider.setMinimum(5)
        self.mean_diameter_slider.setMaximum(300)
        self.mean_diameter_slider.setProperty("value", 40)
        self.mean_diameter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mean_diameter_slider.setObjectName("mean_diameter_slider")
        self.gridLayout_13.addWidget(self.mean_diameter_slider, 2, 2, 1, 1)
        self.generate_map_button = QtGui.QPushButton(self.groupBox_3)
        self.generate_map_button.setMinimumSize(QtCore.QSize(0, 35))
        self.generate_map_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.generate_map_button.setObjectName("generate_map_button")
        self.gridLayout_13.addWidget(self.generate_map_button, 0, 0, 1, 5)
        self.num_obstacles_slider = QtGui.QSlider(self.groupBox_3)
        self.num_obstacles_slider.setMinimum(1)
        self.num_obstacles_slider.setMaximum(250)
        self.num_obstacles_slider.setProperty("value", 50)
        self.num_obstacles_slider.setOrientation(QtCore.Qt.Horizontal)
        self.num_obstacles_slider.setObjectName("num_obstacles_slider")
        self.gridLayout_13.addWidget(self.num_obstacles_slider, 1, 2, 1, 1)
        self.std_dev_diameter_slider = QtGui.QSlider(self.groupBox_3)
        self.std_dev_diameter_slider.setMaximum(100)
        self.std_dev_diameter_slider.setProperty("value", 10)
        self.std_dev_diameter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.std_dev_diameter_slider.setObjectName("std_dev_diameter_slider")
        self.gridLayout_13.addWidget(self.std_dev_diameter_slider, 3, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_3)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.gridLayout_13.addWidget(self.label_36, 3, 1, 1, 1)
        self.polygons_combo = QtGui.QComboBox(self.groupBox_3)
        self.polygons_combo.setObjectName("polygons_combo")
        self.polygons_combo.addItem("")
        self.polygons_combo.addItem("")
        self.gridLayout_13.addWidget(self.polygons_combo, 4, 2, 1, 3)
        self.mean_diameter_box = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.mean_diameter_box.setMinimumSize(QtCore.QSize(75, 0))
        self.mean_diameter_box.setMinimum(0.05)
        self.mean_diameter_box.setMaximum(3.0)
        self.mean_diameter_box.setSingleStep(0.05)
        self.mean_diameter_box.setProperty("value", 0.4)
        self.mean_diameter_box.setObjectName("mean_diameter_box")
        self.gridLayout_13.addWidget(self.mean_diameter_box, 2, 3, 1, 2)
        self.std_dev_diameter_box = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.std_dev_diameter_box.setMinimumSize(QtCore.QSize(75, 0))
        self.std_dev_diameter_box.setMaximum(1.0)
        self.std_dev_diameter_box.setSingleStep(0.01)
        self.std_dev_diameter_box.setProperty("value", 0.1)
        self.std_dev_diameter_box.setObjectName("std_dev_diameter_box")
        self.gridLayout_13.addWidget(self.std_dev_diameter_box, 3, 3, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_3, 2, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayout_10 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_7 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_42 = QtGui.QLabel(self.groupBox_7)
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_18.addWidget(self.label_42, 2, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_7)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_18.addWidget(self.label_40, 2, 0, 1, 1)
        self.toggle_record_button_4 = QtGui.QPushButton(self.groupBox_7)
        self.toggle_record_button_4.setMinimumSize(QtCore.QSize(50, 50))
        self.toggle_record_button_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_record_button_4.setObjectName("toggle_record_button_4")
        self.gridLayout_18.addWidget(self.toggle_record_button_4, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_7)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_18.addWidget(self.label_43, 3, 0, 1, 1)
        self.toggle_record_button_3 = QtGui.QPushButton(self.groupBox_7)
        self.toggle_record_button_3.setMinimumSize(QtCore.QSize(50, 50))
        self.toggle_record_button_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_record_button_3.setObjectName("toggle_record_button_3")
        self.gridLayout_18.addWidget(self.toggle_record_button_3, 1, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_18.addWidget(self.label_41, 3, 1, 1, 1)
        self.record_timer_display_2 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(40)
        font.setWeight(50)
        font.setBold(False)
        self.record_timer_display_2.setFont(font)
        self.record_timer_display_2.setAlignment(QtCore.Qt.AlignCenter)
        self.record_timer_display_2.setObjectName("record_timer_display_2")
        self.gridLayout_18.addWidget(self.record_timer_display_2, 0, 0, 1, 2)
        self.label_44 = QtGui.QLabel(self.groupBox_7)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_18.addWidget(self.label_44, 5, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_18.addWidget(self.label_45, 5, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_7)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_18.addWidget(self.label_46, 4, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_7)
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_18.addWidget(self.label_47, 4, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.record_timer_display = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(40)
        font.setWeight(50)
        font.setBold(False)
        self.record_timer_display.setFont(font)
        self.record_timer_display.setAlignment(QtCore.Qt.AlignCenter)
        self.record_timer_display.setObjectName("record_timer_display")
        self.gridLayout_17.addWidget(self.record_timer_display, 0, 0, 1, 2)
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 2, 0, 1, 1)
        self.record_odom_meas_label = QtGui.QLabel(self.groupBox_5)
        self.record_odom_meas_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.record_odom_meas_label.setObjectName("record_odom_meas_label")
        self.gridLayout_17.addWidget(self.record_odom_meas_label, 3, 1, 1, 1)
        self.record_laser_meas_label = QtGui.QLabel(self.groupBox_5)
        self.record_laser_meas_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.record_laser_meas_label.setObjectName("record_laser_meas_label")
        self.gridLayout_17.addWidget(self.record_laser_meas_label, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_5)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_17.addWidget(self.label_37, 3, 0, 1, 1)
        self.toggle_record_button = QtGui.QPushButton(self.groupBox_5)
        self.toggle_record_button.setMinimumSize(QtCore.QSize(50, 50))
        self.toggle_record_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_record_button.setObjectName("toggle_record_button")
        self.gridLayout_17.addWidget(self.toggle_record_button, 1, 0, 1, 1)
        self.toggle_record_button_2 = QtGui.QPushButton(self.groupBox_5)
        self.toggle_record_button_2.setMinimumSize(QtCore.QSize(50, 50))
        self.toggle_record_button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_record_button_2.setObjectName("toggle_record_button_2")
        self.gridLayout_17.addWidget(self.toggle_record_button_2, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_5, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabWidgetPage3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.laser_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.laser_box.setFont(font)
        self.laser_box.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_box.setObjectName("laser_box")
        self.gridLayout_7 = QtGui.QGridLayout(self.laser_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtGui.QLabel(self.laser_box)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.laser_noise_box = QtGui.QSpinBox(self.laser_box)
        self.laser_noise_box.setMinimum(1)
        self.laser_noise_box.setMaximum(15)
        self.laser_noise_box.setObjectName("laser_noise_box")
        self.gridLayout_8.addWidget(self.laser_noise_box, 8, 2, 1, 1)
        self.laser_res_box = QtGui.QDoubleSpinBox(self.laser_box)
        self.laser_res_box.setMinimum(0.2)
        self.laser_res_box.setMaximum(5.0)
        self.laser_res_box.setSingleStep(0.1)
        self.laser_res_box.setObjectName("laser_res_box")
        self.gridLayout_8.addWidget(self.laser_res_box, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.laser_box)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 1)
        self.laser_range_box = QtGui.QSpinBox(self.laser_box)
        self.laser_range_box.setMinimum(1)
        self.laser_range_box.setMaximum(25)
        self.laser_range_box.setObjectName("laser_range_box")
        self.gridLayout_8.addWidget(self.laser_range_box, 2, 2, 1, 1)
        self.laser_min_bear_box = QtGui.QSpinBox(self.laser_box)
        self.laser_min_bear_box.setMinimum(-180)
        self.laser_min_bear_box.setMaximum(180)
        self.laser_min_bear_box.setProperty("value", -90)
        self.laser_min_bear_box.setObjectName("laser_min_bear_box")
        self.gridLayout_8.addWidget(self.laser_min_bear_box, 4, 2, 1, 1)
        self.laser_res_slider = QtGui.QSlider(self.laser_box)
        self.laser_res_slider.setMinimum(2)
        self.laser_res_slider.setMaximum(50)
        self.laser_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider.setInvertedAppearance(True)
        self.laser_res_slider.setInvertedControls(False)
        self.laser_res_slider.setObjectName("laser_res_slider")
        self.gridLayout_8.addWidget(self.laser_res_slider, 6, 1, 1, 1)
        self.laser_noise_slider = QtGui.QSlider(self.laser_box)
        self.laser_noise_slider.setMinimum(1)
        self.laser_noise_slider.setMaximum(15)
        self.laser_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_noise_slider.setInvertedAppearance(False)
        self.laser_noise_slider.setInvertedControls(False)
        self.laser_noise_slider.setObjectName("laser_noise_slider")
        self.gridLayout_8.addWidget(self.laser_noise_slider, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.laser_box)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 6, 0, 1, 1)
        self.laser_freq_box = QtGui.QSpinBox(self.laser_box)
        self.laser_freq_box.setMinimum(1)
        self.laser_freq_box.setMaximum(15)
        self.laser_freq_box.setObjectName("laser_freq_box")
        self.gridLayout_8.addWidget(self.laser_freq_box, 7, 2, 1, 1)
        self.laser_range_slider = QtGui.QSlider(self.laser_box)
        self.laser_range_slider.setMinimum(1)
        self.laser_range_slider.setMaximum(25)
        self.laser_range_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_range_slider.setObjectName("laser_range_slider")
        self.gridLayout_8.addWidget(self.laser_range_slider, 2, 1, 1, 1)
        self.laser_min_bear_slider = QtGui.QSlider(self.laser_box)
        self.laser_min_bear_slider.setMinimum(-180)
        self.laser_min_bear_slider.setMaximum(180)
        self.laser_min_bear_slider.setProperty("value", -90)
        self.laser_min_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_min_bear_slider.setInvertedAppearance(False)
        self.laser_min_bear_slider.setInvertedControls(False)
        self.laser_min_bear_slider.setObjectName("laser_min_bear_slider")
        self.gridLayout_8.addWidget(self.laser_min_bear_slider, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.laser_box)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.laser_box)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 7, 0, 1, 1)
        self.laser_combo = QtGui.QComboBox(self.laser_box)
        self.laser_combo.setObjectName("laser_combo")
        self.gridLayout_8.addWidget(self.laser_combo, 1, 1, 1, 2)
        self.laser_freq_slider = QtGui.QSlider(self.laser_box)
        self.laser_freq_slider.setMinimum(1)
        self.laser_freq_slider.setMaximum(15)
        self.laser_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_freq_slider.setInvertedAppearance(False)
        self.laser_freq_slider.setInvertedControls(False)
        self.laser_freq_slider.setObjectName("laser_freq_slider")
        self.gridLayout_8.addWidget(self.laser_freq_slider, 7, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.laser_box)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.laser_box)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 5, 0, 1, 1)
        self.laser_max_bear_slider = QtGui.QSlider(self.laser_box)
        self.laser_max_bear_slider.setMinimum(-180)
        self.laser_max_bear_slider.setMaximum(180)
        self.laser_max_bear_slider.setProperty("value", 90)
        self.laser_max_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_max_bear_slider.setInvertedAppearance(False)
        self.laser_max_bear_slider.setInvertedControls(False)
        self.laser_max_bear_slider.setObjectName("laser_max_bear_slider")
        self.gridLayout_8.addWidget(self.laser_max_bear_slider, 5, 1, 1, 1)
        self.laser_max_bear_box = QtGui.QSpinBox(self.laser_box)
        self.laser_max_bear_box.setMinimum(-180)
        self.laser_max_bear_box.setMaximum(180)
        self.laser_max_bear_box.setProperty("value", 90)
        self.laser_max_bear_box.setObjectName("laser_max_bear_box")
        self.gridLayout_8.addWidget(self.laser_max_bear_box, 5, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 3, 6, 1, 1)
        self.gridLayout_4.addWidget(self.laser_box, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_settings_button = QtGui.QPushButton(self.tabWidgetPage3)
        self.load_settings_button.setObjectName("load_settings_button")
        self.horizontalLayout.addWidget(self.load_settings_button)
        self.save_settings_button = QtGui.QPushButton(self.tabWidgetPage3)
        self.save_settings_button.setObjectName("save_settings_button")
        self.horizontalLayout.addWidget(self.save_settings_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.odom_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.odom_box.setFont(font)
        self.odom_box.setAlignment(QtCore.Qt.AlignCenter)
        self.odom_box.setObjectName("odom_box")
        self.gridLayout_5 = QtGui.QGridLayout(self.odom_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtGui.QLabel(self.odom_box)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.odom_freq_box = QtGui.QSpinBox(self.odom_box)
        self.odom_freq_box.setMinimum(1)
        self.odom_freq_box.setMaximum(20)
        self.odom_freq_box.setObjectName("odom_freq_box")
        self.gridLayout_6.addWidget(self.odom_freq_box, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.odom_box)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.odom_freq_slider = QtGui.QSlider(self.odom_box)
        self.odom_freq_slider.setMinimum(1)
        self.odom_freq_slider.setMaximum(20)
        self.odom_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_freq_slider.setInvertedAppearance(False)
        self.odom_freq_slider.setInvertedControls(False)
        self.odom_freq_slider.setObjectName("odom_freq_slider")
        self.gridLayout_6.addWidget(self.odom_freq_slider, 2, 1, 1, 1)
        self.odom_res_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_res_box.setMinimum(0.05)
        self.odom_res_box.setMaximum(2.0)
        self.odom_res_box.setSingleStep(0.05)
        self.odom_res_box.setObjectName("odom_res_box")
        self.gridLayout_6.addWidget(self.odom_res_box, 1, 2, 1, 1)
        self.odom_res_slider = QtGui.QSlider(self.odom_box)
        self.odom_res_slider.setMinimum(5)
        self.odom_res_slider.setMaximum(200)
        self.odom_res_slider.setSingleStep(5)
        self.odom_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_res_slider.setInvertedAppearance(True)
        self.odom_res_slider.setInvertedControls(False)
        self.odom_res_slider.setObjectName("odom_res_slider")
        self.gridLayout_6.addWidget(self.odom_res_slider, 1, 1, 1, 1)
        self.odom_noise_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_noise_box.setMinimum(0.1)
        self.odom_noise_box.setMaximum(3.0)
        self.odom_noise_box.setSingleStep(0.1)
        self.odom_noise_box.setObjectName("odom_noise_box")
        self.gridLayout_6.addWidget(self.odom_noise_box, 3, 2, 1, 1)
        self.odom_noise_slider = QtGui.QSlider(self.odom_box)
        self.odom_noise_slider.setMinimum(1)
        self.odom_noise_slider.setMaximum(30)
        self.odom_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_noise_slider.setInvertedAppearance(False)
        self.odom_noise_slider.setInvertedControls(False)
        self.odom_noise_slider.setObjectName("odom_noise_slider")
        self.gridLayout_6.addWidget(self.odom_noise_slider, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.odom_box)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.odom_box, 1, 0, 1, 1)
        self.robot_box = QtGui.QGroupBox(self.tabWidgetPage3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_box.setFont(font)
        self.robot_box.setAlignment(QtCore.Qt.AlignCenter)
        self.robot_box.setObjectName("robot_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.robot_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robot_wheel_rad_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheel_rad_slider.setMinimum(5)
        self.robot_wheel_rad_slider.setMaximum(50)
        self.robot_wheel_rad_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheel_rad_slider.setInvertedAppearance(False)
        self.robot_wheel_rad_slider.setInvertedControls(False)
        self.robot_wheel_rad_slider.setObjectName("robot_wheel_rad_slider")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_slider, 4, 1, 1, 1)
        self.robot_wheelbase_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheelbase_slider.setMinimum(2)
        self.robot_wheelbase_slider.setMaximum(20)
        self.robot_wheelbase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheelbase_slider.setInvertedAppearance(False)
        self.robot_wheelbase_slider.setInvertedControls(False)
        self.robot_wheelbase_slider.setObjectName("robot_wheelbase_slider")
        self.gridLayout_2.addWidget(self.robot_wheelbase_slider, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.robot_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.robot_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.robot_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_vel_slider.setMinimum(1)
        self.robot_vel_slider.setMaximum(30)
        self.robot_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_vel_slider.setInvertedAppearance(False)
        self.robot_vel_slider.setInvertedControls(False)
        self.robot_vel_slider.setObjectName("robot_vel_slider")
        self.gridLayout_2.addWidget(self.robot_vel_slider, 6, 1, 1, 1)
        self.robot_length_slider = QtGui.QSlider(self.robot_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_length_slider.setFont(font)
        self.robot_length_slider.setMinimum(2)
        self.robot_length_slider.setMaximum(20)
        self.robot_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_length_slider.setObjectName("robot_length_slider")
        self.gridLayout_2.addWidget(self.robot_length_slider, 1, 1, 1, 1)
        self.robot_width_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_width_box.setMinimum(0.2)
        self.robot_width_box.setMaximum(2.0)
        self.robot_width_box.setSingleStep(0.1)
        self.robot_width_box.setObjectName("robot_width_box")
        self.gridLayout_2.addWidget(self.robot_width_box, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.robot_box)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.robot_width_slider = QtGui.QSlider(self.robot_box)
        self.robot_width_slider.setMinimum(2)
        self.robot_width_slider.setMaximum(20)
        self.robot_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_width_slider.setInvertedAppearance(False)
        self.robot_width_slider.setInvertedControls(False)
        self.robot_width_slider.setObjectName("robot_width_slider")
        self.gridLayout_2.addWidget(self.robot_width_slider, 3, 1, 1, 1)
        self.robot_wheel_rad_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheel_rad_box.setMinimum(0.05)
        self.robot_wheel_rad_box.setMaximum(0.5)
        self.robot_wheel_rad_box.setSingleStep(0.01)
        self.robot_wheel_rad_box.setObjectName("robot_wheel_rad_box")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_box, 4, 2, 1, 1)
        self.label = QtGui.QLabel(self.robot_box)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.robot_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.robot_box)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.robot_length_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_length_box.setMinimum(0.2)
        self.robot_length_box.setMaximum(2.0)
        self.robot_length_box.setSingleStep(0.1)
        self.robot_length_box.setObjectName("robot_length_box")
        self.gridLayout_2.addWidget(self.robot_length_box, 1, 2, 1, 1)
        self.robot_ang_vel_box = QtGui.QSpinBox(self.robot_box)
        self.robot_ang_vel_box.setMinimum(5)
        self.robot_ang_vel_box.setMaximum(60)
        self.robot_ang_vel_box.setObjectName("robot_ang_vel_box")
        self.gridLayout_2.addWidget(self.robot_ang_vel_box, 7, 2, 1, 1)
        self.robot_ang_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_ang_vel_slider.setMinimum(5)
        self.robot_ang_vel_slider.setMaximum(60)
        self.robot_ang_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_ang_vel_slider.setInvertedAppearance(False)
        self.robot_ang_vel_slider.setInvertedControls(False)
        self.robot_ang_vel_slider.setObjectName("robot_ang_vel_slider")
        self.gridLayout_2.addWidget(self.robot_ang_vel_slider, 7, 1, 1, 1)
        self.robot_wheelbase_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheelbase_box.setMinimum(0.2)
        self.robot_wheelbase_box.setMaximum(2.0)
        self.robot_wheelbase_box.setSingleStep(0.1)
        self.robot_wheelbase_box.setObjectName("robot_wheelbase_box")
        self.gridLayout_2.addWidget(self.robot_wheelbase_box, 5, 2, 1, 1)
        self.robot_vel_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_vel_box.setMinimum(0.1)
        self.robot_vel_box.setMaximum(3.0)
        self.robot_vel_box.setSingleStep(0.1)
        self.robot_vel_box.setObjectName("robot_vel_box")
        self.gridLayout_2.addWidget(self.robot_vel_box, 6, 2, 1, 1)
        self.robot_combo = QtGui.QComboBox(self.robot_box)
        self.robot_combo.setObjectName("robot_combo")
        self.gridLayout_2.addWidget(self.robot_combo, 0, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.robot_box)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 6, 1, 1)
        self.gridLayout_4.addWidget(self.robot_box, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 3, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "MSL Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("main_window", "Velocity step:", None, QtGui.QApplication.UnicodeUTF8))
        self.vel_inc_box.setSuffix(QtGui.QApplication.translate("main_window", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.pose_label.setText(QtGui.QApplication.translate("main_window", "0.00 m, 0.00 m, -178 deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("main_window", "Ang. vel. step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("main_window", "Show laser:", None, QtGui.QApplication.UnicodeUTF8))
        self.velocity_label.setText(QtGui.QApplication.translate("main_window", "0.4 m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.ang_vel_inc_box.setSuffix(QtGui.QApplication.translate("main_window", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("main_window", "Pose:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("main_window", "Velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in_button.setText(QtGui.QApplication.translate("main_window", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out_button.setText(QtGui.QApplication.translate("main_window", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ang_vel_label.setText(QtGui.QApplication.translate("main_window", "4 deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("main_window", "Zoom:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("main_window", "Angular velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("main_window", "Show map:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("main_window", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.draw_line_button.setText(QtGui.QApplication.translate("main_window", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.freehand_line_button.setText(QtGui.QApplication.translate("main_window", "Freehand", None, QtGui.QApplication.UnicodeUTF8))
        self.line_angle_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("main_window", "Edges:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("main_window", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.line_length_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("main_window", "Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("main_window", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.load_map_button.setText(QtGui.QApplication.translate("main_window", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_map_button.setText(QtGui.QApplication.translate("main_window", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("main_window", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_size_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("main_window", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("main_window", "Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("main_window", "Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_angle_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.draw_polygon_button.setText(QtGui.QApplication.translate("main_window", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.random_polygon_button.setText(QtGui.QApplication.translate("main_window", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_edges_combo.setItemText(0, QtGui.QApplication.translate("main_window", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_edges_combo.setItemText(1, QtGui.QApplication.translate("main_window", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_edges_combo.setItemText(2, QtGui.QApplication.translate("main_window", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.polygon_edges_combo.setItemText(3, QtGui.QApplication.translate("main_window", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_map_button.setText(QtGui.QApplication.translate("main_window", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("main_window", "Full map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("main_window", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("main_window", "Mean diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("main_window", "Num. obstacles", None, QtGui.QApplication.UnicodeUTF8))
        self.generate_map_button.setText(QtGui.QApplication.translate("main_window", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("main_window", "Diameter std. dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.polygons_combo.setItemText(0, QtGui.QApplication.translate("main_window", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.polygons_combo.setItemText(1, QtGui.QApplication.translate("main_window", "User settings", None, QtGui.QApplication.UnicodeUTF8))
        self.mean_diameter_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.std_dev_diameter_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("main_window", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("main_window", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("main_window", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("main_window", "Laser measurements:", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_record_button_4.setText(QtGui.QApplication.translate("main_window", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("main_window", "Odometry measurements:", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_record_button_3.setText(QtGui.QApplication.translate("main_window", "Playback data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("main_window", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.record_timer_display_2.setText(QtGui.QApplication.translate("main_window", "0.0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("main_window", "Playback time :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("main_window", "0.0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("main_window", "Map size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("main_window", "0 lines", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("main_window", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.record_timer_display.setText(QtGui.QApplication.translate("main_window", "0.0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("main_window", "Laser measurements:", None, QtGui.QApplication.UnicodeUTF8))
        self.record_odom_meas_label.setText(QtGui.QApplication.translate("main_window", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.record_laser_meas_label.setText(QtGui.QApplication.translate("main_window", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("main_window", "Odometry measurements:", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_record_button.setText(QtGui.QApplication.translate("main_window", "Start Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_record_button_2.setText(QtGui.QApplication.translate("main_window", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("main_window", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_box.setTitle(QtGui.QApplication.translate("main_window", "Laser ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("main_window", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_noise_box.setSuffix(QtGui.QApplication.translate("main_window", " cm", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_res_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("main_window", "Min bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_range_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_min_bear_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("main_window", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_freq_box.setSuffix(QtGui.QApplication.translate("main_window", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("main_window", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("main_window", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("main_window", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("main_window", "Max bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_max_bear_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.load_settings_button.setText(QtGui.QApplication.translate("main_window", "Load settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_settings_button.setText(QtGui.QApplication.translate("main_window", "Save settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_box.setTitle(QtGui.QApplication.translate("main_window", "Odometry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("main_window", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_freq_box.setSuffix(QtGui.QApplication.translate("main_window", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("main_window", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_res_box.setSuffix(QtGui.QApplication.translate("main_window", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_noise_box.setSuffix(QtGui.QApplication.translate("main_window", " ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("main_window", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_box.setTitle(QtGui.QApplication.translate("main_window", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("main_window", "Wheelbase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main_window", "Max velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_width_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main_window", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheel_rad_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main_window", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("main_window", "Wheel radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("main_window", "Max angular velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_length_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_ang_vel_box.setSuffix(QtGui.QApplication.translate("main_window", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheelbase_box.setSuffix(QtGui.QApplication.translate("main_window", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_vel_box.setSuffix(QtGui.QApplication.translate("main_window", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("main_window", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), QtGui.QApplication.translate("main_window", "Settings", None, QtGui.QApplication.UnicodeUTF8))

from sim.controller import PlotGraphicsViewZoom, PlotGraphicsView
