# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created: Fri Oct 16 09:57:16 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settings_dialog(object):
    def setupUi(self, settings_dialog):
        settings_dialog.setObjectName("settings_dialog")
        settings_dialog.resize(832, 405)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings_dialog.sizePolicy().hasHeightForWidth())
        settings_dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(settings_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(settings_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.general_tab = QtGui.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.general_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtGui.QGroupBox(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 220))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.vel_inc_box = QtGui.QDoubleSpinBox(self.groupBox)
        self.vel_inc_box.setMinimumSize(QtCore.QSize(0, 22))
        self.vel_inc_box.setMaximumSize(QtCore.QSize(90, 16777215))
        self.vel_inc_box.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.vel_inc_box.setMinimum(0.05)
        self.vel_inc_box.setMaximum(0.5)
        self.vel_inc_box.setSingleStep(0.05)
        self.vel_inc_box.setObjectName("vel_inc_box")
        self.gridLayout_9.addWidget(self.vel_inc_box, 0, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 2, 0, 1, 1)
        self.ang_vel_inc_box = QtGui.QSpinBox(self.groupBox)
        self.ang_vel_inc_box.setMinimumSize(QtCore.QSize(0, 22))
        self.ang_vel_inc_box.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ang_vel_inc_box.setMinimum(1)
        self.ang_vel_inc_box.setMaximum(60)
        self.ang_vel_inc_box.setObjectName("ang_vel_inc_box")
        self.gridLayout_9.addWidget(self.ang_vel_inc_box, 1, 1, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.laser_check = QtGui.QCheckBox(self.groupBox)
        self.laser_check.setText("")
        self.laser_check.setChecked(True)
        self.laser_check.setObjectName("laser_check")
        self.horizontalLayout_5.addWidget(self.laser_check)
        self.label_48 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setTextFormat(QtCore.Qt.AutoText)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setWordWrap(False)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.map_check = QtGui.QCheckBox(self.groupBox)
        self.map_check.setText("")
        self.map_check.setChecked(True)
        self.map_check.setObjectName("map_check")
        self.horizontalLayout_5.addWidget(self.map_check)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.general_tab, "")
        self.robot_tab = QtGui.QWidget()
        self.robot_tab.setObjectName("robot_tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.robot_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robot_wheel_rad_slider = QtGui.QSlider(self.robot_tab)
        self.robot_wheel_rad_slider.setMinimum(5)
        self.robot_wheel_rad_slider.setMaximum(50)
        self.robot_wheel_rad_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheel_rad_slider.setInvertedAppearance(False)
        self.robot_wheel_rad_slider.setInvertedControls(False)
        self.robot_wheel_rad_slider.setObjectName("robot_wheel_rad_slider")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_slider, 4, 1, 1, 1)
        self.robot_wheelbase_slider = QtGui.QSlider(self.robot_tab)
        self.robot_wheelbase_slider.setMinimum(2)
        self.robot_wheelbase_slider.setMaximum(20)
        self.robot_wheelbase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheelbase_slider.setInvertedAppearance(False)
        self.robot_wheelbase_slider.setInvertedControls(False)
        self.robot_wheelbase_slider.setObjectName("robot_wheelbase_slider")
        self.gridLayout_2.addWidget(self.robot_wheelbase_slider, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.robot_tab)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.robot_tab)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.robot_vel_slider = QtGui.QSlider(self.robot_tab)
        self.robot_vel_slider.setMinimum(1)
        self.robot_vel_slider.setMaximum(30)
        self.robot_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_vel_slider.setInvertedAppearance(False)
        self.robot_vel_slider.setInvertedControls(False)
        self.robot_vel_slider.setObjectName("robot_vel_slider")
        self.gridLayout_2.addWidget(self.robot_vel_slider, 6, 1, 1, 1)
        self.robot_length_slider = QtGui.QSlider(self.robot_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_length_slider.setFont(font)
        self.robot_length_slider.setMinimum(2)
        self.robot_length_slider.setMaximum(20)
        self.robot_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_length_slider.setObjectName("robot_length_slider")
        self.gridLayout_2.addWidget(self.robot_length_slider, 1, 1, 1, 1)
        self.robot_width_box = QtGui.QDoubleSpinBox(self.robot_tab)
        self.robot_width_box.setMinimum(0.2)
        self.robot_width_box.setMaximum(2.0)
        self.robot_width_box.setSingleStep(0.1)
        self.robot_width_box.setObjectName("robot_width_box")
        self.gridLayout_2.addWidget(self.robot_width_box, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.robot_tab)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.robot_width_slider = QtGui.QSlider(self.robot_tab)
        self.robot_width_slider.setMinimum(2)
        self.robot_width_slider.setMaximum(20)
        self.robot_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_width_slider.setInvertedAppearance(False)
        self.robot_width_slider.setInvertedControls(False)
        self.robot_width_slider.setObjectName("robot_width_slider")
        self.gridLayout_2.addWidget(self.robot_width_slider, 3, 1, 1, 1)
        self.robot_wheel_rad_box = QtGui.QDoubleSpinBox(self.robot_tab)
        self.robot_wheel_rad_box.setMinimum(0.05)
        self.robot_wheel_rad_box.setMaximum(0.5)
        self.robot_wheel_rad_box.setSingleStep(0.01)
        self.robot_wheel_rad_box.setObjectName("robot_wheel_rad_box")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_box, 4, 2, 1, 1)
        self.label = QtGui.QLabel(self.robot_tab)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.robot_tab)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.robot_tab)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.robot_length_box = QtGui.QDoubleSpinBox(self.robot_tab)
        self.robot_length_box.setMinimum(0.2)
        self.robot_length_box.setMaximum(2.0)
        self.robot_length_box.setSingleStep(0.1)
        self.robot_length_box.setObjectName("robot_length_box")
        self.gridLayout_2.addWidget(self.robot_length_box, 1, 2, 1, 1)
        self.robot_ang_vel_box = QtGui.QSpinBox(self.robot_tab)
        self.robot_ang_vel_box.setMinimum(5)
        self.robot_ang_vel_box.setMaximum(60)
        self.robot_ang_vel_box.setObjectName("robot_ang_vel_box")
        self.gridLayout_2.addWidget(self.robot_ang_vel_box, 7, 2, 1, 1)
        self.robot_ang_vel_slider = QtGui.QSlider(self.robot_tab)
        self.robot_ang_vel_slider.setMinimum(5)
        self.robot_ang_vel_slider.setMaximum(60)
        self.robot_ang_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_ang_vel_slider.setInvertedAppearance(False)
        self.robot_ang_vel_slider.setInvertedControls(False)
        self.robot_ang_vel_slider.setObjectName("robot_ang_vel_slider")
        self.gridLayout_2.addWidget(self.robot_ang_vel_slider, 7, 1, 1, 1)
        self.robot_wheelbase_box = QtGui.QDoubleSpinBox(self.robot_tab)
        self.robot_wheelbase_box.setMinimum(0.2)
        self.robot_wheelbase_box.setMaximum(2.0)
        self.robot_wheelbase_box.setSingleStep(0.1)
        self.robot_wheelbase_box.setObjectName("robot_wheelbase_box")
        self.gridLayout_2.addWidget(self.robot_wheelbase_box, 5, 2, 1, 1)
        self.robot_vel_box = QtGui.QDoubleSpinBox(self.robot_tab)
        self.robot_vel_box.setMinimum(0.1)
        self.robot_vel_box.setMaximum(3.0)
        self.robot_vel_box.setSingleStep(0.1)
        self.robot_vel_box.setObjectName("robot_vel_box")
        self.gridLayout_2.addWidget(self.robot_vel_box, 6, 2, 1, 1)
        self.robot_combo = QtGui.QComboBox(self.robot_tab)
        self.robot_combo.setObjectName("robot_combo")
        self.gridLayout_2.addWidget(self.robot_combo, 0, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.robot_tab)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.robot_tab, "")
        self.laser_tab = QtGui.QWidget()
        self.laser_tab.setObjectName("laser_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.laser_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtGui.QLabel(self.laser_tab)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.laser_res_box = QtGui.QDoubleSpinBox(self.laser_tab)
        self.laser_res_box.setMinimum(0.2)
        self.laser_res_box.setMaximum(5.0)
        self.laser_res_box.setSingleStep(0.1)
        self.laser_res_box.setObjectName("laser_res_box")
        self.gridLayout_8.addWidget(self.laser_res_box, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.laser_tab)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 1)
        self.laser_min_bear_box = QtGui.QSpinBox(self.laser_tab)
        self.laser_min_bear_box.setMinimum(-180)
        self.laser_min_bear_box.setMaximum(180)
        self.laser_min_bear_box.setProperty("value", -90)
        self.laser_min_bear_box.setObjectName("laser_min_bear_box")
        self.gridLayout_8.addWidget(self.laser_min_bear_box, 4, 2, 1, 1)
        self.laser_res_slider = QtGui.QSlider(self.laser_tab)
        self.laser_res_slider.setMinimum(2)
        self.laser_res_slider.setMaximum(50)
        self.laser_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider.setInvertedAppearance(True)
        self.laser_res_slider.setInvertedControls(False)
        self.laser_res_slider.setObjectName("laser_res_slider")
        self.gridLayout_8.addWidget(self.laser_res_slider, 6, 1, 1, 1)
        self.laser_noise_slider = QtGui.QSlider(self.laser_tab)
        self.laser_noise_slider.setMinimum(0)
        self.laser_noise_slider.setMaximum(15)
        self.laser_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_noise_slider.setInvertedAppearance(False)
        self.laser_noise_slider.setInvertedControls(False)
        self.laser_noise_slider.setObjectName("laser_noise_slider")
        self.gridLayout_8.addWidget(self.laser_noise_slider, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.laser_tab)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 6, 0, 1, 1)
        self.laser_freq_box = QtGui.QSpinBox(self.laser_tab)
        self.laser_freq_box.setMinimum(1)
        self.laser_freq_box.setMaximum(15)
        self.laser_freq_box.setObjectName("laser_freq_box")
        self.gridLayout_8.addWidget(self.laser_freq_box, 7, 2, 1, 1)
        self.laser_range_slider = QtGui.QSlider(self.laser_tab)
        self.laser_range_slider.setMinimum(1)
        self.laser_range_slider.setMaximum(25)
        self.laser_range_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_range_slider.setObjectName("laser_range_slider")
        self.gridLayout_8.addWidget(self.laser_range_slider, 2, 1, 1, 1)
        self.laser_min_bear_slider = QtGui.QSlider(self.laser_tab)
        self.laser_min_bear_slider.setMinimum(-180)
        self.laser_min_bear_slider.setMaximum(180)
        self.laser_min_bear_slider.setProperty("value", -90)
        self.laser_min_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_min_bear_slider.setInvertedAppearance(False)
        self.laser_min_bear_slider.setInvertedControls(False)
        self.laser_min_bear_slider.setObjectName("laser_min_bear_slider")
        self.gridLayout_8.addWidget(self.laser_min_bear_slider, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.laser_tab)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.laser_tab)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 7, 0, 1, 1)
        self.laser_combo = QtGui.QComboBox(self.laser_tab)
        self.laser_combo.setObjectName("laser_combo")
        self.gridLayout_8.addWidget(self.laser_combo, 1, 1, 1, 2)
        self.laser_freq_slider = QtGui.QSlider(self.laser_tab)
        self.laser_freq_slider.setMinimum(1)
        self.laser_freq_slider.setMaximum(15)
        self.laser_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_freq_slider.setInvertedAppearance(False)
        self.laser_freq_slider.setInvertedControls(False)
        self.laser_freq_slider.setObjectName("laser_freq_slider")
        self.gridLayout_8.addWidget(self.laser_freq_slider, 7, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.laser_tab)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.laser_tab)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 5, 0, 1, 1)
        self.laser_max_bear_slider = QtGui.QSlider(self.laser_tab)
        self.laser_max_bear_slider.setMinimum(-180)
        self.laser_max_bear_slider.setMaximum(180)
        self.laser_max_bear_slider.setProperty("value", 90)
        self.laser_max_bear_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_max_bear_slider.setInvertedAppearance(False)
        self.laser_max_bear_slider.setInvertedControls(False)
        self.laser_max_bear_slider.setObjectName("laser_max_bear_slider")
        self.gridLayout_8.addWidget(self.laser_max_bear_slider, 5, 1, 1, 1)
        self.laser_max_bear_box = QtGui.QSpinBox(self.laser_tab)
        self.laser_max_bear_box.setMinimum(-180)
        self.laser_max_bear_box.setMaximum(180)
        self.laser_max_bear_box.setProperty("value", 90)
        self.laser_max_bear_box.setObjectName("laser_max_bear_box")
        self.gridLayout_8.addWidget(self.laser_max_bear_box, 5, 2, 1, 1)
        self.laser_range_box = QtGui.QSpinBox(self.laser_tab)
        self.laser_range_box.setMinimum(1)
        self.laser_range_box.setMaximum(25)
        self.laser_range_box.setObjectName("laser_range_box")
        self.gridLayout_8.addWidget(self.laser_range_box, 2, 2, 1, 1)
        self.laser_noise_box = QtGui.QDoubleSpinBox(self.laser_tab)
        self.laser_noise_box.setMinimum(0.0)
        self.laser_noise_box.setMaximum(0.15)
        self.laser_noise_box.setSingleStep(0.01)
        self.laser_noise_box.setObjectName("laser_noise_box")
        self.gridLayout_8.addWidget(self.laser_noise_box, 8, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.laser_tab, "")
        self.encoder_tab = QtGui.QWidget()
        self.encoder_tab.setObjectName("encoder_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.encoder_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtGui.QLabel(self.encoder_tab)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.odom_freq_box = QtGui.QSpinBox(self.encoder_tab)
        self.odom_freq_box.setMinimum(1)
        self.odom_freq_box.setMaximum(20)
        self.odom_freq_box.setObjectName("odom_freq_box")
        self.gridLayout_6.addWidget(self.odom_freq_box, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.encoder_tab)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.odom_freq_slider = QtGui.QSlider(self.encoder_tab)
        self.odom_freq_slider.setMinimum(1)
        self.odom_freq_slider.setMaximum(20)
        self.odom_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_freq_slider.setInvertedAppearance(False)
        self.odom_freq_slider.setInvertedControls(False)
        self.odom_freq_slider.setObjectName("odom_freq_slider")
        self.gridLayout_6.addWidget(self.odom_freq_slider, 2, 1, 1, 1)
        self.odom_res_box = QtGui.QDoubleSpinBox(self.encoder_tab)
        self.odom_res_box.setMinimum(0.05)
        self.odom_res_box.setMaximum(2.0)
        self.odom_res_box.setSingleStep(0.05)
        self.odom_res_box.setObjectName("odom_res_box")
        self.gridLayout_6.addWidget(self.odom_res_box, 1, 2, 1, 1)
        self.odom_res_slider = QtGui.QSlider(self.encoder_tab)
        self.odom_res_slider.setMinimum(5)
        self.odom_res_slider.setMaximum(200)
        self.odom_res_slider.setSingleStep(5)
        self.odom_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_res_slider.setInvertedAppearance(True)
        self.odom_res_slider.setInvertedControls(False)
        self.odom_res_slider.setObjectName("odom_res_slider")
        self.gridLayout_6.addWidget(self.odom_res_slider, 1, 1, 1, 1)
        self.odom_noise_box = QtGui.QDoubleSpinBox(self.encoder_tab)
        self.odom_noise_box.setMinimum(0.1)
        self.odom_noise_box.setMaximum(3.0)
        self.odom_noise_box.setSingleStep(0.1)
        self.odom_noise_box.setObjectName("odom_noise_box")
        self.gridLayout_6.addWidget(self.odom_noise_box, 3, 2, 1, 1)
        self.odom_noise_slider = QtGui.QSlider(self.encoder_tab)
        self.odom_noise_slider.setMinimum(1)
        self.odom_noise_slider.setMaximum(30)
        self.odom_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_noise_slider.setInvertedAppearance(False)
        self.odom_noise_slider.setInvertedControls(False)
        self.odom_noise_slider.setObjectName("odom_noise_slider")
        self.gridLayout_6.addWidget(self.odom_noise_slider, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.encoder_tab)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.encoder_tab, "")
        self.gyro_tab = QtGui.QWidget()
        self.gyro_tab.setObjectName("gyro_tab")
        self.gridLayout_11 = QtGui.QGridLayout(self.gyro_tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gyro_freq_box = QtGui.QSpinBox(self.gyro_tab)
        self.gyro_freq_box.setMinimum(1)
        self.gyro_freq_box.setMaximum(100)
        self.gyro_freq_box.setObjectName("gyro_freq_box")
        self.gridLayout_10.addWidget(self.gyro_freq_box, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.gyro_tab)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 1, 0, 1, 1)
        self.gyro_freq_slider = QtGui.QSlider(self.gyro_tab)
        self.gyro_freq_slider.setMinimum(1)
        self.gyro_freq_slider.setMaximum(100)
        self.gyro_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gyro_freq_slider.setInvertedAppearance(False)
        self.gyro_freq_slider.setInvertedControls(False)
        self.gyro_freq_slider.setObjectName("gyro_freq_slider")
        self.gridLayout_10.addWidget(self.gyro_freq_slider, 1, 1, 1, 1)
        self.gyro_noise_box = QtGui.QDoubleSpinBox(self.gyro_tab)
        self.gyro_noise_box.setDecimals(2)
        self.gyro_noise_box.setMinimum(0.0)
        self.gyro_noise_box.setMaximum(3.0)
        self.gyro_noise_box.setSingleStep(0.05)
        self.gyro_noise_box.setObjectName("gyro_noise_box")
        self.gridLayout_10.addWidget(self.gyro_noise_box, 2, 2, 1, 1)
        self.gyro_noise_slider = QtGui.QSlider(self.gyro_tab)
        self.gyro_noise_slider.setMinimum(1)
        self.gyro_noise_slider.setMaximum(300)
        self.gyro_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gyro_noise_slider.setInvertedAppearance(False)
        self.gyro_noise_slider.setInvertedControls(False)
        self.gyro_noise_slider.setObjectName("gyro_noise_slider")
        self.gridLayout_10.addWidget(self.gyro_noise_slider, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gyro_tab)
        self.label_19.setMinimumSize(QtCore.QSize(120, 0))
        self.label_19.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.gyro_tab, "")
        self.compass_tab = QtGui.QWidget()
        self.compass_tab.setObjectName("compass_tab")
        self.gridLayout_13 = QtGui.QGridLayout(self.compass_tab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_24 = QtGui.QLabel(self.compass_tab)
        self.label_24.setMinimumSize(QtCore.QSize(120, 0))
        self.label_24.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 1, 0, 1, 1)
        self.compass_noise_slider = QtGui.QSlider(self.compass_tab)
        self.compass_noise_slider.setMinimum(0)
        self.compass_noise_slider.setMaximum(50)
        self.compass_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.compass_noise_slider.setInvertedAppearance(False)
        self.compass_noise_slider.setInvertedControls(False)
        self.compass_noise_slider.setObjectName("compass_noise_slider")
        self.gridLayout_12.addWidget(self.compass_noise_slider, 1, 1, 1, 1)
        self.compass_noise_box = QtGui.QDoubleSpinBox(self.compass_tab)
        self.compass_noise_box.setDecimals(0)
        self.compass_noise_box.setMinimum(0.0)
        self.compass_noise_box.setMaximum(50.0)
        self.compass_noise_box.setSingleStep(1.0)
        self.compass_noise_box.setObjectName("compass_noise_box")
        self.gridLayout_12.addWidget(self.compass_noise_box, 1, 2, 1, 1)
        self.compass_freq_slider = QtGui.QSlider(self.compass_tab)
        self.compass_freq_slider.setMinimum(1)
        self.compass_freq_slider.setMaximum(100)
        self.compass_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.compass_freq_slider.setObjectName("compass_freq_slider")
        self.gridLayout_12.addWidget(self.compass_freq_slider, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.compass_tab)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 0, 0, 1, 1)
        self.compass_freq_box = QtGui.QSpinBox(self.compass_tab)
        self.compass_freq_box.setMinimum(1)
        self.compass_freq_box.setMaximum(100)
        self.compass_freq_box.setObjectName("compass_freq_box")
        self.gridLayout_12.addWidget(self.compass_freq_box, 0, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.compass_tab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_29 = QtGui.QGridLayout(self.tab)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_53 = QtGui.QLabel(self.tab)
        self.label_53.setMinimumSize(QtCore.QSize(120, 0))
        self.label_53.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_28.addWidget(self.label_53, 1, 0, 1, 1)
        self.gps_noise_slider = QtGui.QSlider(self.tab)
        self.gps_noise_slider.setMinimum(0)
        self.gps_noise_slider.setMaximum(1000)
        self.gps_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gps_noise_slider.setInvertedAppearance(False)
        self.gps_noise_slider.setInvertedControls(False)
        self.gps_noise_slider.setObjectName("gps_noise_slider")
        self.gridLayout_28.addWidget(self.gps_noise_slider, 1, 1, 1, 1)
        self.gps_noise_box = QtGui.QDoubleSpinBox(self.tab)
        self.gps_noise_box.setDecimals(2)
        self.gps_noise_box.setMinimum(0.0)
        self.gps_noise_box.setMaximum(10.0)
        self.gps_noise_box.setSingleStep(1.0)
        self.gps_noise_box.setObjectName("gps_noise_box")
        self.gridLayout_28.addWidget(self.gps_noise_box, 1, 2, 1, 1)
        self.gps_freq_slider = QtGui.QSlider(self.tab)
        self.gps_freq_slider.setMinimum(1)
        self.gps_freq_slider.setMaximum(100)
        self.gps_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gps_freq_slider.setObjectName("gps_freq_slider")
        self.gridLayout_28.addWidget(self.gps_freq_slider, 0, 1, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_28.addWidget(self.label_54, 0, 0, 1, 1)
        self.gps_freq_box = QtGui.QSpinBox(self.tab)
        self.gps_freq_box.setMinimum(1)
        self.gps_freq_box.setMaximum(100)
        self.gps_freq_box.setObjectName("gps_freq_box")
        self.gridLayout_28.addWidget(self.gps_freq_box, 0, 2, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(settings_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(settings_dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), settings_dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), settings_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslateUi(self, settings_dialog):
        settings_dialog.setWindowTitle(QtGui.QApplication.translate("settings_dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("settings_dialog", "Velocity step:", None, QtGui.QApplication.UnicodeUTF8))
        self.vel_inc_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("settings_dialog", "Show laser:", None, QtGui.QApplication.UnicodeUTF8))
        self.ang_vel_inc_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("settings_dialog", "Show map:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("settings_dialog", "Ang. vel. step:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), QtGui.QApplication.translate("settings_dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settings_dialog", "Wheelbase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settings_dialog", "Max velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_width_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settings_dialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheel_rad_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settings_dialog", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settings_dialog", "Wheel radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settings_dialog", "Max angular velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_length_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_ang_vel_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_wheelbase_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_vel_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("settings_dialog", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.robot_tab), QtGui.QApplication.translate("settings_dialog", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("settings_dialog", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_res_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("settings_dialog", "Min bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_min_bear_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("settings_dialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_freq_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("settings_dialog", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("settings_dialog", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("settings_dialog", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("settings_dialog", "Max bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_max_bear_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_range_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_noise_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.laser_tab), QtGui.QApplication.translate("settings_dialog", "Laser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("settings_dialog", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_freq_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("settings_dialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_res_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_noise_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settings_dialog", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encoder_tab), QtGui.QApplication.translate("settings_dialog", "Encoders", None, QtGui.QApplication.UnicodeUTF8))
        self.gyro_freq_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("settings_dialog", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.gyro_noise_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("settings_dialog", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gyro_tab), QtGui.QApplication.translate("settings_dialog", "Gyro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("settings_dialog", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.compass_noise_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("settings_dialog", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.compass_freq_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compass_tab), QtGui.QApplication.translate("settings_dialog", "Compass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("settings_dialog", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.gps_noise_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("settings_dialog", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.gps_freq_box.setSuffix(QtGui.QApplication.translate("settings_dialog", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settings_dialog", "GPS", None, QtGui.QApplication.UnicodeUTF8))

