# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim/view/laser.ui'
#
# Created: Thu May 23 22:27:34 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_laser(object):
    def setupUi(self, laser):
        laser.setObjectName("laser")
        laser.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(laser)
        self.gridLayout.setObjectName("gridLayout")
        self.laser_box = QtGui.QGroupBox(laser)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.laser_box.setFont(font)
        self.laser_box.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_box.setObjectName("laser_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.laser_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_range_slider = QtGui.QSlider(self.laser_box)
        self.laser_range_slider.setMinimum(1)
        self.laser_range_slider.setMaximum(25)
        self.laser_range_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_range_slider.setObjectName("laser_range_slider")
        self.gridLayout_2.addWidget(self.laser_range_slider, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.laser_box)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.laser_fov_slider = QtGui.QSlider(self.laser_box)
        self.laser_fov_slider.setMinimum(10)
        self.laser_fov_slider.setMaximum(360)
        self.laser_fov_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_fov_slider.setInvertedAppearance(False)
        self.laser_fov_slider.setInvertedControls(False)
        self.laser_fov_slider.setObjectName("laser_fov_slider")
        self.gridLayout_2.addWidget(self.laser_fov_slider, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.laser_box)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.laser_fov_box = QtGui.QSpinBox(self.laser_box)
        self.laser_fov_box.setMinimum(10)
        self.laser_fov_box.setMaximum(360)
        self.laser_fov_box.setObjectName("laser_fov_box")
        self.gridLayout_2.addWidget(self.laser_fov_box, 2, 2, 1, 1)
        self.laser_range_box = QtGui.QSpinBox(self.laser_box)
        self.laser_range_box.setMinimum(1)
        self.laser_range_box.setMaximum(25)
        self.laser_range_box.setObjectName("laser_range_box")
        self.gridLayout_2.addWidget(self.laser_range_box, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.laser_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.laser_res_box = QtGui.QDoubleSpinBox(self.laser_box)
        self.laser_res_box.setMinimum(0.2)
        self.laser_res_box.setMaximum(5.0)
        self.laser_res_box.setSingleStep(0.1)
        self.laser_res_box.setObjectName("laser_res_box")
        self.gridLayout_2.addWidget(self.laser_res_box, 3, 2, 1, 1)
        self.laser_res_slider = QtGui.QSlider(self.laser_box)
        self.laser_res_slider.setMinimum(2)
        self.laser_res_slider.setMaximum(50)
        self.laser_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider.setInvertedAppearance(False)
        self.laser_res_slider.setInvertedControls(False)
        self.laser_res_slider.setObjectName("laser_res_slider")
        self.gridLayout_2.addWidget(self.laser_res_slider, 3, 1, 1, 1)
        self.laser_freq_slider = QtGui.QSlider(self.laser_box)
        self.laser_freq_slider.setMinimum(1)
        self.laser_freq_slider.setMaximum(15)
        self.laser_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.laser_freq_slider.setInvertedAppearance(False)
        self.laser_freq_slider.setInvertedControls(False)
        self.laser_freq_slider.setObjectName("laser_freq_slider")
        self.gridLayout_2.addWidget(self.laser_freq_slider, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.laser_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.laser_freq_box = QtGui.QSpinBox(self.laser_box)
        self.laser_freq_box.setMinimum(1)
        self.laser_freq_box.setMaximum(15)
        self.laser_freq_box.setObjectName("laser_freq_box")
        self.gridLayout_2.addWidget(self.laser_freq_box, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.laser_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.laser_res_slider_2 = QtGui.QSlider(self.laser_box)
        self.laser_res_slider_2.setMinimum(1)
        self.laser_res_slider_2.setMaximum(15)
        self.laser_res_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.laser_res_slider_2.setInvertedAppearance(False)
        self.laser_res_slider_2.setInvertedControls(False)
        self.laser_res_slider_2.setObjectName("laser_res_slider_2")
        self.gridLayout_2.addWidget(self.laser_res_slider_2, 5, 1, 1, 1)
        self.laser_freq_box_2 = QtGui.QSpinBox(self.laser_box)
        self.laser_freq_box_2.setMinimum(1)
        self.laser_freq_box_2.setMaximum(15)
        self.laser_freq_box_2.setObjectName("laser_freq_box_2")
        self.gridLayout_2.addWidget(self.laser_freq_box_2, 5, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 6, 1, 1)
        self.gridLayout.addWidget(self.laser_box, 0, 0, 1, 1)

        self.retranslateUi(laser)
        QtCore.QObject.connect(self.laser_range_slider, QtCore.SIGNAL("valueChanged(int)"), self.laser_range_box.setValue)
        QtCore.QObject.connect(self.laser_range_box, QtCore.SIGNAL("valueChanged(int)"), self.laser_range_slider.setValue)
        QtCore.QObject.connect(self.laser_fov_slider, QtCore.SIGNAL("valueChanged(int)"), self.laser_fov_box.setValue)
        QtCore.QObject.connect(self.laser_fov_box, QtCore.SIGNAL("valueChanged(int)"), self.laser_fov_slider.setValue)
        QtCore.QObject.connect(self.laser_freq_slider, QtCore.SIGNAL("valueChanged(int)"), self.laser_freq_box.setValue)
        QtCore.QObject.connect(self.laser_freq_box, QtCore.SIGNAL("valueChanged(int)"), self.laser_freq_slider.setValue)
        QtCore.QObject.connect(self.laser_res_slider_2, QtCore.SIGNAL("valueChanged(int)"), self.laser_freq_box_2.setValue)
        QtCore.QObject.connect(self.laser_freq_box_2, QtCore.SIGNAL("valueChanged(int)"), self.laser_res_slider_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(laser)

    def retranslateUi(self, laser):
        laser.setWindowTitle(QtGui.QApplication.translate("laser", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_box.setTitle(QtGui.QApplication.translate("laser", "Laser Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("laser", "FOV [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("laser", "Range [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("laser", "Resolution [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("laser", "Frequency [Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("laser", "Noise [cm]", None, QtGui.QApplication.UnicodeUTF8))

