# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim/view/odometry.ui'
#
# Created: Thu May 23 22:30:15 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_odometry(object):
    def setupUi(self, odometry):
        odometry.setObjectName("odometry")
        odometry.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(odometry)
        self.gridLayout.setObjectName("gridLayout")
        self.odom_box = QtGui.QGroupBox(odometry)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.odom_box.setFont(font)
        self.odom_box.setAlignment(QtCore.Qt.AlignCenter)
        self.odom_box.setObjectName("odom_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.odom_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.odom_freq_slider = QtGui.QSlider(self.odom_box)
        self.odom_freq_slider.setMinimum(1)
        self.odom_freq_slider.setMaximum(30)
        self.odom_freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_freq_slider.setInvertedAppearance(False)
        self.odom_freq_slider.setInvertedControls(False)
        self.odom_freq_slider.setObjectName("odom_freq_slider")
        self.gridLayout_2.addWidget(self.odom_freq_slider, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.odom_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.odom_res_slider = QtGui.QSlider(self.odom_box)
        self.odom_res_slider.setMinimum(5)
        self.odom_res_slider.setMaximum(30)
        self.odom_res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_res_slider.setInvertedAppearance(False)
        self.odom_res_slider.setInvertedControls(False)
        self.odom_res_slider.setObjectName("odom_res_slider")
        self.gridLayout_2.addWidget(self.odom_res_slider, 1, 1, 1, 1)
        self.odom_res_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_res_box.setMinimum(0.5)
        self.odom_res_box.setMaximum(3.0)
        self.odom_res_box.setSingleStep(0.1)
        self.odom_res_box.setObjectName("odom_res_box")
        self.gridLayout_2.addWidget(self.odom_res_box, 1, 2, 1, 1)
        self.odom_noise_slider = QtGui.QSlider(self.odom_box)
        self.odom_noise_slider.setMinimum(1)
        self.odom_noise_slider.setMaximum(30)
        self.odom_noise_slider.setOrientation(QtCore.Qt.Horizontal)
        self.odom_noise_slider.setInvertedAppearance(False)
        self.odom_noise_slider.setInvertedControls(False)
        self.odom_noise_slider.setObjectName("odom_noise_slider")
        self.gridLayout_2.addWidget(self.odom_noise_slider, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.odom_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.odom_freq_box = QtGui.QSpinBox(self.odom_box)
        self.odom_freq_box.setMinimum(1)
        self.odom_freq_box.setMaximum(30)
        self.odom_freq_box.setObjectName("odom_freq_box")
        self.gridLayout_2.addWidget(self.odom_freq_box, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.odom_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.odom_noise_box = QtGui.QDoubleSpinBox(self.odom_box)
        self.odom_noise_box.setMinimum(0.1)
        self.odom_noise_box.setMaximum(3.0)
        self.odom_noise_box.setSingleStep(0.1)
        self.odom_noise_box.setObjectName("odom_noise_box")
        self.gridLayout_2.addWidget(self.odom_noise_box, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 6, 1, 1)
        self.gridLayout.addWidget(self.odom_box, 0, 0, 1, 1)

        self.retranslateUi(odometry)
        QtCore.QObject.connect(self.odom_freq_slider, QtCore.SIGNAL("valueChanged(int)"), self.odom_freq_box.setValue)
        QtCore.QObject.connect(self.odom_freq_box, QtCore.SIGNAL("valueChanged(int)"), self.odom_freq_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(odometry)

    def retranslateUi(self, odometry):
        odometry.setWindowTitle(QtGui.QApplication.translate("odometry", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.odom_box.setTitle(QtGui.QApplication.translate("odometry", "Odometry Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("odometry", "Resolution [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("odometry", "Noise [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("odometry", "Frequency [Hz]", None, QtGui.QApplication.UnicodeUTF8))

