# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim/view/robot.ui'
#
# Created: Thu May 23 22:27:52 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_robot(object):
    def setupUi(self, robot):
        robot.setObjectName("robot")
        robot.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(robot)
        self.gridLayout.setObjectName("gridLayout")
        self.robot_box = QtGui.QGroupBox(robot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_box.setFont(font)
        self.robot_box.setAlignment(QtCore.Qt.AlignCenter)
        self.robot_box.setObjectName("robot_box")
        self.gridLayout_3 = QtGui.QGridLayout(self.robot_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robot_wheel_rad_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheel_rad_slider.setMinimum(10)
        self.robot_wheel_rad_slider.setMaximum(50)
        self.robot_wheel_rad_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheel_rad_slider.setInvertedAppearance(False)
        self.robot_wheel_rad_slider.setInvertedControls(False)
        self.robot_wheel_rad_slider.setObjectName("robot_wheel_rad_slider")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_slider, 3, 1, 1, 1)
        self.robot_wheelbase_slider = QtGui.QSlider(self.robot_box)
        self.robot_wheelbase_slider.setMinimum(5)
        self.robot_wheelbase_slider.setMaximum(20)
        self.robot_wheelbase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_wheelbase_slider.setInvertedAppearance(False)
        self.robot_wheelbase_slider.setInvertedControls(False)
        self.robot_wheelbase_slider.setObjectName("robot_wheelbase_slider")
        self.gridLayout_2.addWidget(self.robot_wheelbase_slider, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.robot_box)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.robot_box)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.robot_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_vel_slider.setMinimum(1)
        self.robot_vel_slider.setMaximum(30)
        self.robot_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_vel_slider.setInvertedAppearance(False)
        self.robot_vel_slider.setInvertedControls(False)
        self.robot_vel_slider.setObjectName("robot_vel_slider")
        self.gridLayout_2.addWidget(self.robot_vel_slider, 5, 1, 1, 1)
        self.robot_width_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_width_box.setMinimum(0.5)
        self.robot_width_box.setMaximum(2.0)
        self.robot_width_box.setSingleStep(0.1)
        self.robot_width_box.setObjectName("robot_width_box")
        self.gridLayout_2.addWidget(self.robot_width_box, 2, 2, 1, 1)
        self.robot_length_slider = QtGui.QSlider(self.robot_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.robot_length_slider.setFont(font)
        self.robot_length_slider.setMinimum(5)
        self.robot_length_slider.setMaximum(20)
        self.robot_length_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_length_slider.setObjectName("robot_length_slider")
        self.gridLayout_2.addWidget(self.robot_length_slider, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.robot_box)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.robot_width_slider = QtGui.QSlider(self.robot_box)
        self.robot_width_slider.setMinimum(5)
        self.robot_width_slider.setMaximum(20)
        self.robot_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_width_slider.setInvertedAppearance(False)
        self.robot_width_slider.setInvertedControls(False)
        self.robot_width_slider.setObjectName("robot_width_slider")
        self.gridLayout_2.addWidget(self.robot_width_slider, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.robot_box)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.robot_box)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.robot_wheel_rad_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheel_rad_box.setMinimum(0.1)
        self.robot_wheel_rad_box.setMaximum(0.5)
        self.robot_wheel_rad_box.setSingleStep(0.01)
        self.robot_wheel_rad_box.setObjectName("robot_wheel_rad_box")
        self.gridLayout_2.addWidget(self.robot_wheel_rad_box, 3, 2, 1, 1)
        self.robot_length_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_length_box.setMinimum(0.5)
        self.robot_length_box.setMaximum(2.0)
        self.robot_length_box.setSingleStep(0.1)
        self.robot_length_box.setObjectName("robot_length_box")
        self.gridLayout_2.addWidget(self.robot_length_box, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.robot_box)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.robot_ang_vel_slider = QtGui.QSlider(self.robot_box)
        self.robot_ang_vel_slider.setMinimum(5)
        self.robot_ang_vel_slider.setMaximum(60)
        self.robot_ang_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.robot_ang_vel_slider.setInvertedAppearance(False)
        self.robot_ang_vel_slider.setInvertedControls(False)
        self.robot_ang_vel_slider.setObjectName("robot_ang_vel_slider")
        self.gridLayout_2.addWidget(self.robot_ang_vel_slider, 6, 1, 1, 1)
        self.robot_ang_vel_box = QtGui.QSpinBox(self.robot_box)
        self.robot_ang_vel_box.setMinimum(5)
        self.robot_ang_vel_box.setMaximum(60)
        self.robot_ang_vel_box.setObjectName("robot_ang_vel_box")
        self.gridLayout_2.addWidget(self.robot_ang_vel_box, 6, 2, 1, 1)
        self.robot_wheelbase_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_wheelbase_box.setMinimum(0.5)
        self.robot_wheelbase_box.setMaximum(2.0)
        self.robot_wheelbase_box.setSingleStep(0.1)
        self.robot_wheelbase_box.setObjectName("robot_wheelbase_box")
        self.gridLayout_2.addWidget(self.robot_wheelbase_box, 4, 2, 1, 1)
        self.robot_vel_box = QtGui.QDoubleSpinBox(self.robot_box)
        self.robot_vel_box.setMinimum(0.1)
        self.robot_vel_box.setMaximum(3.0)
        self.robot_vel_box.setSingleStep(0.1)
        self.robot_vel_box.setObjectName("robot_vel_box")
        self.gridLayout_2.addWidget(self.robot_vel_box, 5, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 6, 1, 1)
        self.gridLayout.addWidget(self.robot_box, 0, 0, 1, 1)

        self.retranslateUi(robot)
        QtCore.QObject.connect(self.robot_ang_vel_slider, QtCore.SIGNAL("valueChanged(int)"), self.robot_ang_vel_box.setValue)
        QtCore.QObject.connect(self.robot_ang_vel_box, QtCore.SIGNAL("valueChanged(int)"), self.robot_ang_vel_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(robot)

    def retranslateUi(self, robot):
        robot.setWindowTitle(QtGui.QApplication.translate("robot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_box.setTitle(QtGui.QApplication.translate("robot", "Robot Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("robot", "Wheelbase [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("robot", "Max velocity [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("robot", "Width [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("robot", "Length [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("robot", "Wheel radius [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("robot", "Max angular velocity [deg/s]", None, QtGui.QApplication.UnicodeUTF8))

